#include "path_follow.h"
#include "motor.h"
#include "pid.h"
#include "zf_device_ips200.h"
#include <math.h>
#include "Attitude.h"
#include "BlueSerial.h"

/**
 * @file path_follow.c
 * @brief 璺緞璺熼殢涓庡簳鐩橀€熷害瑙勫垝瀹炵幇鏂囦欢銆?
 *
 * 鏈枃浠惰礋璐ｅ皢涓婂眰缁欏嚭鐨勮矾寰勭偣鎴栨嫄鐐瑰簭鍒楄浆鎹负搴曠洏鍙墽琛岀殑杩炵画閫熷害鍛戒护锛?
 * 鎺у埗杩囩▼渚濇缁忚繃璺緞鍑犱綍鍒嗘瀽銆佹爣閲忛€熷害瑙勫垝銆佸Э鎬佹帶鍒跺拰杞︿綋绯婚€熷害鍚堟垚銆?
 * 褰撳墠瀹炵幇鍏煎缃戞牸鍦板浘浜х敓鐨勬í骞崇珫鐩磋矾寰勶紝骞朵繚鐣欏惎鍔ㄥ亸绉汇€佷綅濮挎牎姝ｇ瓑杈呭姪鍔ㄤ綔鎺ュ彛銆?
 */


#ifndef M_PI
#define M_PI 3.1415926
#endif

/** @brief 鎺ヨ繎鐩爣鐐规椂寮€濮嬫贩鍚堝畾鐐逛繚鎸佷慨姝ｇ殑璺濈闃堝€硷紝鍗曚綅 m銆?*/
#define PATH_HOLD_TRIM_RELEASE_DISTANCE 0.25f

/*
 * Target compensation, unit: cm.
 * compensated_target = raw_target + BASE_COMP_CM + accumulated_axis_run_cm * RUN_COMP_K.
 * RUN_COMP_K means compensation cm per accumulated 1 cm run on that axis.
 */
#define PATH_FOLLOW_TARGET_X_BASE_COMP_CM 0.0f
#define PATH_FOLLOW_TARGET_X_RUN_COMP_K -0.01666f
#define PATH_FOLLOW_TARGET_Y_BASE_COMP_CM 0.0f
#define PATH_FOLLOW_TARGET_Y_RUN_COMP_K 0.01666f
/* Extra X target compensation generated by accumulated Y-axis run, unit: cm/cm. */
#define PATH_FOLLOW_TARGET_X_FROM_Y_RUN_COMP_K 0.023f
/** @brief 鐩寸嚎娈垫硶鍚戠籂鍋忔瘮渚嬬郴鏁帮紝鍗曚綅 (cm/s)/cm銆?*/
#define PATH_LINE_GUIDE_KP 1.0f
/**
 * @brief 鐩寸嚎娈垫硶鍚戠籂鍋忕殑鏈€灏忎慨姝ｉ€熷害锛屽崟浣?cm/s銆?
 *
 * 浣滅敤锛?
 * - 褰撴í鍚戣宸垰鍒氳秴杩囨鍖烘椂锛屽崟绾?Kp 鍙兘涓嶈冻浠ュ厠鏈嶉潤鎽╂摝锛?
 * - 杩欓噷棰濆缁欎竴涓€滄渶灏忎晶鍚戜慨姝ｉ€熷害鍓嶉鈥濓紝甯姪灏忚溅鍏堝姩璧锋潵銆?
 *
 * 璋冨弬寤鸿锛?
 * - 璁句负 0 鍙€€鍥炲埌鍘熸潵鐨勭函 Kp 绾犲亸锛?
 * - 鑻ヤ粛鎺ㄤ笉鍔紝鍙€愭澧炲ぇ锛?
 * - 鑻ュ嚭鐜版槑鏄炬潵鍥炴娊鍔紝鍙€傚綋鍑忓皬銆?
 */
#define PATH_LINE_GUIDE_MIN_CMPS 5.0f
/** @brief 鐩寸嚎娈垫硶鍚戠籂鍋忛€熷害闄愬箙锛屽崟浣?cm/s銆?*/
#define PATH_LINE_GUIDE_MAX_CMPS 12.0f
/** @brief 鐩寸嚎娈垫硶鍚戠籂鍋忔鍖猴紝鍗曚綅 m銆?*/
#define PATH_LINE_GUIDE_DEADBAND_M 0.005f
/** @brief 鏄惁鍚敤鐩寸嚎娈垫硶鍚戠籂鍋忥細1 鍚敤锛? 鍏抽棴銆?*/
#define PATH_FOLLOW_ENABLE_LINE_GUIDE 1

/** @brief 闈炵粓鐐硅矾寰勬鍦ㄦ鏈繚	鐣欑殑杩囨浮閫熷害锛屽崟浣?cm/s銆?*/
#define SCURVE_SEGMENT_END_SPEED_CMPS 0.0f
/** @brief S 鏇茬嚎 band 0 鐨勮窛绂讳笂闄愶紝鍗曚綅 m銆?*/
#define PATH_FOLLOW_SCURVE_BAND0_UPPER_M 0.30f
/** @brief S 鏇茬嚎 band 1 鐨勮窛绂讳笂闄愶紝鍗曚綅 m銆?*/
#define PATH_FOLLOW_SCURVE_BAND1_UPPER_M 0.50f
/** @brief S 鏇茬嚎 band 2 鐨勮窛绂讳笂闄愶紝鍗曚綅 m銆?*/
#define PATH_FOLLOW_SCURVE_BAND2_UPPER_M 0.70f
/** @brief S 鏇茬嚎 band 3 鐨勮窛绂讳笂闄愶紝鍗曚綅 m銆?*/
#define PATH_FOLLOW_SCURVE_BAND3_UPPER_M 0.90f
/** @brief S 鏇茬嚎鏈€鍚庝竴涓?band 鐨勫厹搴曡窛绂讳笂闄愶紝鍗曚綅 m銆?*/
#define PATH_FOLLOW_SCURVE_LAST_UPPER_M 1000.0f
/** @brief 褰撳墠鏈攣瀹氫换浣?band 鏃剁殑鏃犳晥绱㈠紩銆?*/
#define PATH_FOLLOW_INVALID_SCURVE_BAND_IDX 0xFFU
/** @brief 鍚姩鍋忕Щ涓庡畾浣嶄慨姝ｄ复鏃惰矾寰勭殑绂绘暎鍒嗚鲸鐜囷紝鍗曚綅 m銆?*/
#define PRESTART_OFFSET_RESOLUTION_M 0.01f
/** @brief 鎷愮偣闄勮繎鏄惁鍚敤鍙岃酱 PID 淇濇寔淇锛? 鍚敤锛? 鍏抽棴銆?*/
#define PATH_FOLLOW_ENABLE_CORNER_DUAL_AXIS_TRIM 1
/** @brief 鍚敤鎷愮偣 handover 鏃讹紝鎷愮偣鍙岃酱淇濇寔淇鐨勬潈閲嶇缉鏀剧郴鏁般€?*/
#define PATH_FOLLOW_CORNER_HOLD_TRIM_SCALE 9.0f
/** @brief 鏅€氫腑闂存嫄鐐规槸鍚﹀惎鐢ㄩ€熷害鍚戦噺 handover锛? 鍚敤锛? 鍥為€€鍒板師濮嬬畝鍗曟鏈€熷害淇濈暀銆?*/
#define PATH_FOLLOW_ENABLE_CORNER_HANDOVER 0
/** @brief 缂栬瘧鎷愮偣 handover 浠ｇ爜锛屽疄闄呮槸鍚﹀惎鐢ㄧ敱杩愯鏃惰皟鍙傚彉閲忔帶鍒躲€?*/
#define PATH_FOLLOW_COMPILE_CORNER_HANDOVER 0
#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER


/* [CornerHandover閲嶆瀯] 淇濊瘉 enter / commit 绐楀彛涔嬮棿鑷冲皯鐣欏嚭鐨勮窛绂伙紝鍗曚綅 m銆?*/
#define PATH_CORNER_HANDOVER_WINDOW_GAP_MIN_M 0.005f
/* [CornerHandover閲嶆瀯] 鏅€氫腑闂存嫄鐐规寮忓垏娈垫椂鐨勬渶灏忔í鍚戣宸棬闄愶紝鍗曚綅 m銆?*/
#define PATH_CORNER_COMMIT_LATERAL_GATE_MIN_M 0.02f
/* [CornerHandover閲嶆瀯] 鏅€氫腑闂存嫄鐐规寮忓垏娈垫椂妯悜璇樊闂ㄩ檺鐩稿 pos_tol 鐨勬斁澶х郴鏁般€?*/
#define PATH_CORNER_COMMIT_LATERAL_GATE_SCALE 1.20f
/* [CornerHandover閲嶆瀯] 浜ゆ帴涓瀵规爣閲忛€熷害鍋氳交寰帇浣庯紝閬垮厤鎷愮偣鍒囧悜閫熷害杩囩‖銆?*/
#define PATH_CORNER_HANDOVER_K_DROP 0.16f
/* [CornerHandover] 鍥哄畾浜ゆ帴绐楀彛鐨勫紑濮嬭窛绂伙紝鍗曚綅 m銆?*/
#define PATH_CORNER_HANDOVER_ENTER_DISTANCE_M 0.15f
/* [CornerHandover] 鍥哄畾浜ゆ帴绐楀彛鐨勬湯绔窛绂伙紝鍗曚綅 m銆?*/
#define PATH_CORNER_HANDOVER_COMMIT_DISTANCE_M 0.015f
/* [CornerHandover] 鍗曚釜鎷愮偣浜ゆ帴鏈€澶氬厑璁告寔缁殑鏃堕棿锛屽崟浣?s銆?*/
#define PATH_CORNER_HANDOVER_TIMEOUT_S 5U

#endif

#ifndef PATH_CORNER_HANDOVER_WINDOW_GAP_MIN_M
#define PATH_CORNER_HANDOVER_WINDOW_GAP_MIN_M 0.005f
#endif
#ifndef PATH_CORNER_COMMIT_LATERAL_GATE_MIN_M
#define PATH_CORNER_COMMIT_LATERAL_GATE_MIN_M 0.01f
#endif
#ifndef PATH_CORNER_COMMIT_LATERAL_GATE_SCALE
#define PATH_CORNER_COMMIT_LATERAL_GATE_SCALE 1.20f
#endif
#ifndef PATH_CORNER_HANDOVER_K_DROP
#define PATH_CORNER_HANDOVER_K_DROP 0.16f
#endif
#ifndef PATH_CORNER_HANDOVER_ENTER_DISTANCE_M
#define PATH_CORNER_HANDOVER_ENTER_DISTANCE_M 0.15f
#endif
#ifndef PATH_CORNER_HANDOVER_COMMIT_DISTANCE_M
#define PATH_CORNER_HANDOVER_COMMIT_DISTANCE_M 0.015f
#endif
#ifndef PATH_CORNER_HANDOVER_TIMEOUT_S
#define PATH_CORNER_HANDOVER_TIMEOUT_S 5U
#endif

/** @brief 璺緞璺熼殢鍒扮偣鍒ゅ畾鐨勫熀纭€浣嶇疆瀹瑰樊锛屽崟浣?m銆?*/
#define PATH_FOLLOW_POSITION_TOLERANCE_M 0.01
/** @brief 鍘熷湴杞悜瀹屾垚鍒ゅ畾鐨勮埅鍚戝宸紝鍗曚綅 deg銆?*/
#define PATH_FOLLOW_YAW_TOLERANCE_DEG 1.0f
/** @brief 璺緞璺熼殢鍏佽鐨勭嚎閫熷害涓婇檺锛屽崟浣?m/s銆?*/
#define PATH_FOLLOW_MAX_LINEAR_SPEED_MPS 3.0f
/**
 * @brief 褰撳墠瀹炵幇涓Э鎬佺幆杈撳嚭闄愬箙浣跨敤鐨勮閫熷害涓婇檺鏁板€笺€?
 *
 * @note 璇ュ€肩洿鎺ユ部鐢ㄧ幇鏈夊疄鐜颁腑鐨勬暟鍊艰涔夛紝鍙仛瀹忔娊鍙栵紝涓嶆敼鍙樺綋鍓嶆帶鍒舵鏋躲€?
 */
#define PATH_FOLLOW_MAX_ANGULAR_SPEED_LIMIT 360.0f

/** @brief 涓栫晫绯讳綅缃幆 PID 姣斾緥绯绘暟銆?*/
#define PATH_FOLLOW_PID_WORLD_KP 4.2f
/** @brief 涓栫晫绯讳綅缃幆 PID 绉垎绯绘暟銆?*/
#define PATH_FOLLOW_PID_WORLD_KI 0.0f
/** @brief 涓栫晫绯讳綅缃幆 PID 寰垎绯绘暟銆?*/
#define PATH_FOLLOW_PID_WORLD_KD 1.8f
/** @brief 涓栫晫绯讳綅缃幆 D 椤规护娉㈢郴鏁般€?*/
#define PATH_FOLLOW_PID_WORLD_ALPHA 0.9f

/** @brief 杩戠洰鏍囦繚鎸佷綅缃幆 PID 姣斾緥绯绘暟銆?*/
#define PATH_FOLLOW_PID_STAY_KP 0.7f
/** @brief 杩戠洰鏍囦繚鎸佷綅缃幆 PID 绉垎绯绘暟銆?*/
#define PATH_FOLLOW_PID_STAY_KI 0.0f
/** @brief 杩戠洰鏍囦繚鎸佷綅缃幆 PID 寰垎绯绘暟銆?*/
#define PATH_FOLLOW_PID_STAY_KD 0.3f
/** @brief 杩戠洰鏍囦繚鎸佷綅缃幆绉垎闄愬箙锛屽崟浣?cm/s銆?*/
#define PATH_FOLLOW_PID_STAY_MAX_IOUT_CMPS 200.0f
/** @brief 杩戠洰鏍囦繚鎸佷綅缃幆杈撳嚭闄愬箙锛屽崟浣?cm/s銆?*/
#define PATH_FOLLOW_PID_STAY_MAX_OUT_CMPS 200.0f
/** @brief 杩戠洰鏍囦繚鎸佷綅缃幆 D 椤规护娉㈢郴鏁般€?*/
#define PATH_FOLLOW_PID_STAY_ALPHA 0.9f

/** @brief 鑸悜鐜?PID 姣斾緥绯绘暟銆?*/
#define PATH_FOLLOW_PID_YAW_KP 8.2f
/** @brief 鑸悜鐜?PID 绉垎绯绘暟銆?*/
#define PATH_FOLLOW_PID_YAW_KI 0.0f
/** @brief 鑸悜鐜?PID 寰垎绯绘暟銆?*/
#define PATH_FOLLOW_PID_YAW_KD 8.5f
/** @brief 鑸悜鐜?D 椤规护娉㈢郴鏁般€?*/
#define PATH_FOLLOW_PID_YAW_ALPHA 0.9f

/** @brief 棰勭暀濮挎€佹墿灞曠幆 PID 姣斾緥绯绘暟銆?*/
#define PATH_FOLLOW_PID_ACCEL_YAW_KP 1.2f
/** @brief 棰勭暀濮挎€佹墿灞曠幆 PID 绉垎绯绘暟銆?*/
#define PATH_FOLLOW_PID_ACCEL_YAW_KI 0.0f
/** @brief 棰勭暀濮挎€佹墿灞曠幆 PID 寰垎绯绘暟銆?*/
#define PATH_FOLLOW_PID_ACCEL_YAW_KD 2.1f
/** @brief 棰勭暀濮挎€佹墿灞曠幆 D 椤规护娉㈢郴鏁般€?*/
#define PATH_FOLLOW_PID_ACCEL_YAW_ALPHA 0.9f

/**
 * @brief 涓栫晫鍧愭爣绯讳笅鐨勪簩缁翠綅濮裤€?
 */
typedef struct
{
    float x_m;      // 涓栫晫鍧愭爣绯?X锛屽崟浣?m
    float y_m;      // 涓栫晫鍧愭爣绯?Y锛屽崟浣?m
    float yaw_deg;  // 鑸悜瑙掞紝搴?
} pose2d_t;

/**
 * @brief 濮挎€佹帶鍒舵ā寮忔灇涓俱€?
 */
typedef enum
{
    PATH_FOLLOW_HEADING_FIXED = 0
} path_follow_heading_mode_t;

/**
 * @brief 閫熷害瑙勫垝鍙傛暟闆嗗悎銆?
 */
typedef struct
{
    float segment_end_speed_cmps;   // 闈炵粓鐐硅矾寰勬鍦ㄦ鏈繚鐣欑殑鐩爣閫熷害锛屽崟浣?cm/s
    float hold_release_distance_m;  // 寮€濮嬫贩鍚堝畾鐐逛繚鎸佷慨姝ｇ殑璺濈闃堝€硷紝鍗曚綅 m
} path_follow_speed_cfg_t;

/**
 * @brief 褰撳墠璺緞娈甸攣瀹氱殑 S 鏇茬嚎 band 杩愯鍙傛暟銆?
 */
typedef struct
{
    uint8 band_idx;         // 褰撳墠璺緞娈甸攣瀹氱殑 band 绱㈠紩
    float max_speed_cmps;   // 褰撳墠璺緞娈甸攣瀹氱殑鏈€澶ч€熷害锛屽崟浣?cm/s
    float accel_cmpss;      // 褰撳墠璺緞娈甸攣瀹氱殑鏈€澶у姞閫熷害锛屽崟浣?cm/s^2
    float jerk_cmpsss;      // 褰撳墠璺緞娈甸攣瀹氱殑鏈€澶?jerk锛屽崟浣?cm/s^3
} path_follow_scurve_runtime_cfg_t;

/**
 * @brief 璺緞鍑犱綍灞傝緭鍑恒€?
 */
typedef struct
{
    Position target_point; // 褰撳墠鐩爣绂绘暎鐐?
    float target_x_m;      // 褰撳墠鐩爣鐐?X 鍧愭爣锛屽崟浣?m
    float target_y_m;      // 褰撳墠鐩爣鐐?Y 鍧愭爣锛屽崟浣?m
    float delta_x_m;       // 鐩爣鐩稿褰撳墠浣嶇疆鐨?X 鏂瑰悜璇樊锛屽崟浣?m
    float delta_y_m;       // 鐩爣鐩稿褰撳墠浣嶇疆鐨?Y 鏂瑰悜璇樊锛屽崟浣?m
    float distance_m;      // 褰撳墠鐩爣鐐规姘忚窛绂伙紝鍗曚綅 m
    float dir_x;           // 鎸囧悜鐩爣鐨勫崟浣嶆柟鍚戝悜閲?X 鍒嗛噺
    float dir_y;           // 鎸囧悜鐩爣鐨勫崟浣嶆柟鍚戝悜閲?Y 鍒嗛噺
    uint8 segment_axis;    // 褰撳墠娈典富杞寸被鍨?
} path_follow_geometry_t;

/**
 * @brief 閫熷害瑙勫垝灞傝緭鍑恒€?
 */
typedef struct
{
    float safety_cap_cmps; // 浠呯敤浜庡紓甯镐繚鎶ょ殑瀹夊叏閫熷害涓婇檺锛屽崟浣?cm/s
    float end_speed_cmps;  // 褰撳墠娈垫湯绔洰鏍囬€熷害锛屽崟浣?cm/s
    float ref_speed_cmps;  // 鏈懆鏈熸渶缁堟爣閲忛€熷害鍙傝€冿紝鍗曚綅 cm/s
} path_follow_speed_plan_t;

/**
 * @brief 褰撳墠璺緞娈电殑鏍囧噯 7 娈?jerk-limited S 鏇茬嚎鍙傛暟銆?
 *
 * @note 鏈粨鏋勬弿杩扮殑鏄€滀竴鏉¤矾寰勬涓€娆℃€ц鍒掑畬鎴愨€濈殑瀹屾暣 profile锛?
 *       鍚庣画鎺у埗鍛ㄦ湡鍙寜绱鏃堕棿閲囨牱锛屼笉鍐嶆粴鍔ㄩ噸寤恒€?
 */
typedef struct
{
    float s;      // 褰撳墠璺緞娈垫€讳綅绉伙紝鍗曚綅 cm
    float x0;     // 杞ㄨ抗璧风偣浣嶇疆锛屽崟浣?cm锛屽綋鍓嶅疄鐜板浐瀹氫负 0
    float x1;     // 杞ㄨ抗缁堢偣浣嶇疆锛屽崟浣?cm
    float v0;     // 娈佃捣鐐归€熷害锛屽崟浣?cm/s
    float v1;     // 娈电粓鐐归€熷害锛屽崟浣?cm/s
    float vmax;   // 閰嶇疆缁欏畾鐨勬渶澶ч€熷害绾︽潫锛屽崟浣?cm/s
    float amax;   // 鏈潯杞ㄨ抗鏈€缁堥噰鐢ㄧ殑鏈€澶у姞閫熷害锛屽崟浣?cm/s^2
    float jmax;   // 鏈潯杞ㄨ抗閲囩敤鐨勬渶澶?jerk锛屽崟浣?cm/s^3
    float vlim;   // 鏈潯杞ㄨ抗瀹為檯鍙揪鍒扮殑宄板€奸€熷害锛屽崟浣?cm/s
    float alima;  // 鍔犻€熶晶瀹為檯宄板€煎姞閫熷害锛屽崟浣?cm/s^2
    float alimd;  // 鍑忛€熶晶瀹為檯宄板€煎噺閫熷害骞呭€硷紝鍗曚綅 cm/s^2
    float Tj1;    // 鍔犻€熶晶 jerk 浣滅敤鏃堕棿锛屽崟浣?s
    float Ta;     // 鏁翠釜鍔犻€熼樁娈垫椂闀匡紝鍗曚綅 s
    float Tv;     // 鍖€閫熼樁娈垫椂闀匡紝鍗曚綅 s
    float Tj2;    // 鍑忛€熶晶 jerk 浣滅敤鏃堕棿锛屽崟浣?s
    float Td;     // 鏁翠釜鍑忛€熼樁娈垫椂闀匡紝鍗曚綅 s
    float T;      // 杞ㄨ抗鎬绘椂闀匡紝鍗曚綅 s
    uint8 valid;
} path_follow_scurve_profile_t;

/**
 * @brief 濮挎€佸眰杈撳嚭銆?
 */
typedef struct
{
    float target_yaw_deg;   // 褰撳墠濮挎€佸眰鐩爣鑸悜锛屽崟浣?deg
    float omega_cmd_radps;  // 褰撳墠濮挎€佸眰杈撳嚭瑙掗€熷害锛屽崟浣?rad/s
} path_follow_attitude_plan_t;

/**
 * @brief 杞︿綋杩愬姩鍛戒护缂撳瓨銆?
 */
typedef struct
{
    float vx_world_cmps;  // 涓栫晫绯?X 鏂瑰悜閫熷害鍛戒护锛屽崟浣?cm/s
    float vy_world_cmps;  // 涓栫晫绯?Y 鏂瑰悜閫熷害鍛戒护锛屽崟浣?cm/s
    float vx_body_cmps;   // 杞︿綋绯?X 鏂瑰悜閫熷害鍛戒护锛屽崟浣?cm/s
    float vy_body_cmps;   // 杞︿綋绯?Y 鏂瑰悜閫熷害鍛戒护锛屽崟浣?cm/s
} path_follow_motion_cmd_t;

/**
 * @brief 璋冭瘯鐘舵€佸揩鐓с€?
 */
typedef struct
{
    float distance_m;       // 褰撳墠鐩爣璺濈锛屽崟浣?m
    float dir_x;            // 褰撳墠鍗曚綅鏂瑰悜鍚戦噺 X 鍒嗛噺
    float dir_y;            // 褰撳墠鍗曚綅鏂瑰悜鍚戦噺 Y 鍒嗛噺
    float speed_ref_cmps;   // 褰撳墠鏍囬噺閫熷害鍙傝€冿紝鍗曚綅 cm/s
    float target_yaw_deg;   // 褰撳墠鐩爣鑸悜锛屽崟浣?deg
    float vx_world_cmps;    // 褰撳墠涓栫晫绯?X 閫熷害鍛戒护锛屽崟浣?cm/s
    float vy_world_cmps;    // 褰撳墠涓栫晫绯?Y 閫熷害鍛戒护锛屽崟浣?cm/s
    uint8 segment_axis;     // 褰撳墠璺緞娈典富杞寸被鍨?
} path_follow_debug_state_t;

/**
 * @brief 璺緞璺熼殢妯″潡杩愯涓婁笅鏂囥€?
 */
typedef struct
{
    const Position *path;  // 瑙勫垝璺緞鎸囬拡
    size_t steps;          // 璺緞闀垮害
    size_t idx;            // 褰撳墠鐩爣鐐圭储寮?
    float grid_m;          // 缃戞牸杈归暱锛宮/鏍?
    float default_grid_m;  // 鍦板浘璺緞缃戞牸杈归暱锛宮/鏍?
    float pulses_per_meter;// 缂栫爜鍣ㄦ瘡绫宠剦鍐叉暟
    float pos_tol_m;       // 浣嶇疆瀹瑰樊
    float yaw_tol_deg;     // 鑸悜瀹瑰樊锛堜繚鐣欙紝褰撳墠鏈敤锛?
    float max_v_mps;       // 绾块€熷害涓婇檺 m/s
    float max_w_rad;       // 瑙掗€熷害涓婇檺 rad/s
    float target_yaw_deg;  // 褰撳墠濮挎€佹帶鍒剁洰鏍?
    uint8 heading_mode;    // 褰撳墠濮挎€佹帶鍒舵ā寮?
    pose2d_t pose;         // 褰撳墠閲岀▼璁′綅濮?
    path_follow_speed_cfg_t speed_cfg;          // 閫熷害瑙勫垝鍙傛暟闆嗗悎
    path_follow_scurve_runtime_cfg_t active_scurve_cfg; // 褰撳墠璺緞娈甸攣瀹氱殑 S 鏇茬嚎鍙傛暟
    path_follow_scurve_profile_t active_profile;// 褰撳墠鐩爣娈电殑鏁存寮?S 鏇茬嚎 profile
    path_follow_debug_state_t debug;            // 璋冭瘯鐘舵€佸揩鐓?
    float profile_time_s;                       // 褰撳墠 profile 宸叉墽琛岀殑绱鏃堕棿
    float last_ref_speed_cmps;                 // 涓婁竴鍛ㄦ湡杈撳嚭鐨勬爣閲忛€熷害鍙傝€?
    size_t profile_target_idx;                 // 褰撳墠 profile 缁戝畾鐨勭洰鏍囩偣绱㈠紩
    size_t pause_indices[PATH_FOLLOW_MAX_PAUSE_POINTS]; // 闇€瑕佸湪鍒扮偣鍚庢殏鍋滅殑 corner 绱㈠紩鍒楄〃
    size_t pause_count;                        // pause_indices 涓殑鏈夋晥鍏冪礌涓暟
    size_t pause_cursor;                       // 涓嬩竴涓緟瑙﹀彂鐨勬殏鍋滅偣娓告爣
    uint32 pause_cycles_cfg;                   // 姣忔鏆傚仠缁熶竴鎸佺画鐨勬帶鍒跺懆鏈熸暟
    uint32 pause_cycles_remaining;             // 褰撳墠鏆傚仠鍓╀綑鎺у埗鍛ㄦ湡鏁?
    uint8 pause_events_enabled;                // 浠呮櫘閫氬湴鍥?corner_path 鍏佽瑙﹀彂鏆傚仠
    uint8 paused;                              // 1: 姝ｅ浜庢殏鍋滅獥鍙?
    uint8 rotate_only_active;                  // 1: 褰撳墠浠呮墽琛屽師鍦拌浆鍚?
    uint8 profile_active;                      // 1: 褰撳墠娈靛凡鏈夋湁鏁?profile
#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER
    uint8 corner_handover_active;              // 1: 褰撳墠鏅€氫腑闂存嫄鐐瑰凡杩涘叆 handover 鍖?
    size_t corner_handover_idx;                // 褰撳墠 handover 瀵瑰簲鐨?target idx
    float corner_enter_distance_m;             // 褰撳墠鎷愮偣杩涘叆 handover 鐨勮窛绂婚槇鍊硷紝鍗曚綅 m
    float corner_commit_distance_m;            // 褰撳墠鎷愮偣鍏佽姝ｅ紡鍒囨鐨勬彁鍓嶉噺锛屽崟浣?m
#endif
    uint8 active;                              // 1: 姝ｅ湪璺熼殢
} path_follow_ctx_t;

/** @brief 璺緞璺熼殢妯″潡鍏ㄥ眬涓婁笅鏂囥€?*/
static path_follow_ctx_t g_ctx = {0};
/** @brief 榛樿鐨?S 鏇茬嚎 band 閰嶇疆琛ㄣ€?*/
static const path_follow_scurve_band_cfg_t g_path_follow_scurve_band_default_cfg[PATH_FOLLOW_SCURVE_BAND_COUNT] = {
    {PATH_FOLLOW_SCURVE_BAND0_UPPER_M, 0.40f, 0.60f, 3.00f},
    {PATH_FOLLOW_SCURVE_BAND1_UPPER_M, 0.50f, 0.70f, 3.50f},
    {PATH_FOLLOW_SCURVE_BAND2_UPPER_M, 0.65f, 0.80f, 4.00f},
    {PATH_FOLLOW_SCURVE_BAND3_UPPER_M, 0.75f, 0.85f, 4.70f},
    {PATH_FOLLOW_SCURVE_LAST_UPPER_M, 1.50f, 0.95f, 5.50f},
};
/** @brief 瀵瑰鍙皟鐨?S 鏇茬嚎 band 閰嶇疆琛ㄣ€?*/
path_follow_scurve_band_cfg_t g_path_follow_scurve_band_cfg[PATH_FOLLOW_SCURVE_BAND_COUNT] = {
    {PATH_FOLLOW_SCURVE_BAND0_UPPER_M, 0.40f, 0.60f, 3.00f},
    {PATH_FOLLOW_SCURVE_BAND1_UPPER_M, 0.50f, 0.70f, 3.50f},
    {PATH_FOLLOW_SCURVE_BAND2_UPPER_M, 0.65f, 0.80f, 4.00f},
    {PATH_FOLLOW_SCURVE_BAND3_UPPER_M, 0.75f, 0.85f, 4.70f},
    {PATH_FOLLOW_SCURVE_LAST_UPPER_M, 1.50f, 0.95f, 5.50f},
};
/** @brief 鍘嗗彶 X 杞翠綅缃幆 PID锛屽綋鍓嶄富瑕佷繚鐣欏弬鏁颁笌鍏煎鎺ュ彛銆?*/
tagPID_T pid_world_x;
/** @brief 鍘嗗彶 Y 杞翠綅缃幆 PID锛屽綋鍓嶄富瑕佷繚鐣欏弬鏁颁笌鍏煎鎺ュ彛銆?*/
tagPID_T pid_world_y;
/** @brief 杩戠洰鏍囦繚鎸佷娇鐢ㄧ殑 X 杞?PID銆?*/
tagPID_T pid_stay;
/** @brief 杩戠洰鏍囦繚鎸佷娇鐢ㄧ殑 Y 杞?PID銆?*/
tagPID_T pid_stay_y;
/** @brief 鑸悜鎺у埗 PID銆?*/
tagPID_T pid_yaw;
/** @brief 棰勭暀鐨勫Э鎬佹墿灞?PID銆?*/
tagPID_T pid_accel_yaw;

/** @brief X/Y 浣嶇疆鐜垵濮嬪寲鍙傛暟銆?*/
static PIDInitStruct pid_world_init;
/** @brief 瀹氱偣淇濇寔 PID 鍒濆鍖栧弬鏁般€?*/
static PIDInitStruct pid_stay_init;
/** @brief 鑸悜 PID 鍒濆鍖栧弬鏁般€?*/
static PIDInitStruct pid_yaw_init;
/** @brief 棰勭暀濮挎€佹墿灞?PID 鍒濆鍖栧弬鏁般€?*/
static PIDInitStruct pid_accel_yaw_init;
/** @brief 褰撳墠璺緞娈典富杞存爣璁帮細0 鍋滄锛? X 娈碉紝2 Y 娈碉紝3 鏂滄銆?*/
uint8 car_direction = 0;
/** @brief 澶栧眰淇濈暀鐨勫仠杞︾瓑寰呮爣蹇椼€?*/
uint8 wait_stop = 0;
/** @brief 鍙戣溅鍓嶅乏绉诲亸缃噺锛屽崟浣?m銆?*/
float prestart_move_left_m = 0.12f;
/** @brief 鍙戣溅鍓嶅彸绉诲亸缃噺锛屽崟浣?m銆?*/
float prestart_move_right_m = 0.00f;
/** @brief 鍙戣溅鍓嶅墠绉诲亸缃噺锛屽崟浣?m銆?*/
float prestart_move_forward_m = 0.35f;
/** @brief 鍙戣溅鍓嶅悗绉诲亸缃噺锛屽崟浣?m銆?*/
float prestart_move_backward_m = 0.00f;
float path_corner_commit_lateral_gate_min_m = PATH_CORNER_COMMIT_LATERAL_GATE_MIN_M;
uint8 path_follow_enable_corner_handover = PATH_FOLLOW_ENABLE_CORNER_HANDOVER;
float path_hold_trim_release_distance = PATH_HOLD_TRIM_RELEASE_DISTANCE;
float path_line_guide_kp = PATH_LINE_GUIDE_KP;
float path_follow_corner_hold_trim_scale = PATH_FOLLOW_CORNER_HOLD_TRIM_SCALE;
float path_line_guide_min_cmps = PATH_LINE_GUIDE_MIN_CMPS;
float path_corner_handover_enter_distance_m = PATH_CORNER_HANDOVER_ENTER_DISTANCE_M;
float path_corner_handover_commit_distance_m = PATH_CORNER_HANDOVER_COMMIT_DISTANCE_M;
/** @brief 鍗曠洰鏍囨ā寮忎娇鐢ㄧ殑涓ょ偣涓存椂璺緞缂撳瓨銆?*/
static Position g_single_target_path[2];
/** @brief 鍙戣溅鍓嶅亸绉诲姩浣滀娇鐢ㄧ殑涓存椂璺緞缂撳瓨銆?*/
static Position g_prestart_offset_path[3];
/** @brief 浣嶅Э淇鍔ㄤ綔浣跨敤鐨勪复鏃惰矾寰勭紦瀛樸€?*/
static Position g_pose_correction_path[3];
/** @brief 钃濈墮浣嶇疆涓婃姤鎸傝捣鏍囧織锛岀敱 10ms 鎺у埗鑺傛媿缃綅銆佷富寰幆娑堣垂銆?*/
static volatile uint8 g_path_follow_bt_report_pending = 0U;

/**
 * @brief 瀵硅緭鍏ュ€煎仛瀵圭О闄愬箙銆?
 *
 * @param v 寰呴檺骞呰緭鍏ュ€笺€?
 * @param limit 姝ｅ悜涓庤礋鍚戝叡鐢ㄧ殑闄愬箙缁濆鍊笺€?
 * @return 闄愬箙鍚庣殑缁撴灉銆?
 */
static float clamp_sym(float v, float limit)
{
    if (v > limit)
    {
        return limit;
    }
    if (v < -limit)
    {
        return -limit;
    }
    return v;
}

/**
 * @brief 灏嗗姬搴﹀綊涓€鍖栧埌 (-pi, pi] 鍖洪棿銆?
 *
 * @param rad 鍘熷寮у害鍊笺€?
 * @return 褰掍竴鍖栧悗鐨勫姬搴﹀€笺€?
 */
static float wrap_pi(float rad)
{
    while (rad > (float)M_PI)
    {
        rad -= 2.0f * (float)M_PI;
    }
    while (rad < -(float)M_PI)
    {
        rad += 2.0f * (float)M_PI;
    }
    return rad;
}

static float path_follow_wrap_deg(float deg)
{
    while (deg > 180.0f)
    {
        deg -= 360.0f;
    }
    while (deg < -180.0f)
    {
        deg += 360.0f;
    }
    return deg;
}

static float path_follow_yaw_error_deg(float current_yaw_deg, float target_yaw_deg)
{
    return path_follow_wrap_deg(target_yaw_deg - current_yaw_deg);
}

/**
 * @brief 灏?m/s 杞垚 cm/s銆?
 */
static float path_follow_mps_to_cmps(float value_mps)
{
    return value_mps * 100.0f;
}

/**
 * @brief 灏?m/s^2 杞垚 cm/s^2銆?
 */
static float path_follow_mps2_to_cmpss(float value_mps2)
{
    return value_mps2 * 100.0f;
}

/**
 * @brief 灏?m/s^3 杞垚 cm/s^3銆?
 */
static float path_follow_mps3_to_cmpsss(float value_mps3)
{
    return value_mps3 * 100.0f;
}

static float path_follow_get_accumulated_axis_run_cm(size_t target_idx, uint8 x_axis)
{
    size_t i;
    float run_cm = 0.0f;

    if (g_ctx.path == NULL || g_ctx.steps == 0U)
    {
        return 0.0f;
    }
    if (target_idx >= g_ctx.steps)
    {
        target_idx = g_ctx.steps - 1U;
    }

    for (i = 1U; i <= target_idx; ++i)
    {
        int delta_grid = x_axis ?
                         (g_ctx.path[i].row - g_ctx.path[i - 1U].row) :
                         (g_ctx.path[i].col - g_ctx.path[i - 1U].col);
        run_cm += fabsf((float)delta_grid) * g_ctx.grid_m * 100.0f;
    }

    return run_cm;
}

static float path_follow_compute_target_comp_cm(float base_comp_cm,
                                                float axis_run_cm,
                                                float run_comp_k)
{
    return base_comp_cm + axis_run_cm * run_comp_k;
}

static float path_follow_grid_delta_sign(int delta_grid)
{
    if (delta_grid > 0)
    {
        return 1.0f;
    }
    if (delta_grid < 0)
    {
        return -1.0f;
    }
    return 0.0f;
}

static void path_follow_get_raw_target_position(Position target,
                                                float *target_x_m,
                                                float *target_y_m)
{
    if (target_x_m != NULL)
    {
        *target_x_m = target.row * g_ctx.grid_m;
    }
    if (target_y_m != NULL)
    {
        *target_y_m = target.col * g_ctx.grid_m;
    }
}

static void path_follow_get_segment_target_comp_cm(size_t target_idx,
                                                   float *x_comp_cm,
                                                   float *y_comp_cm)
{
    int delta_row = 0;
    int delta_col = 0;
    float x_run_cm = 0.0f;
    float y_run_cm = 0.0f;
    float x_dir = 0.0f;
    float y_dir = 0.0f;
    float x_comp = PATH_FOLLOW_TARGET_X_BASE_COMP_CM;
    float y_comp = PATH_FOLLOW_TARGET_Y_BASE_COMP_CM;

    if (g_ctx.path != NULL && target_idx > 0U && target_idx < g_ctx.steps)
    {
        delta_row = g_ctx.path[target_idx].row - g_ctx.path[target_idx - 1U].row;
        delta_col = g_ctx.path[target_idx].col - g_ctx.path[target_idx - 1U].col;
        x_run_cm = fabsf((float)delta_row) * g_ctx.grid_m * 100.0f;
        y_run_cm = fabsf((float)delta_col) * g_ctx.grid_m * 100.0f;
        x_dir = path_follow_grid_delta_sign(delta_row);
        y_dir = path_follow_grid_delta_sign(delta_col);
    }

    x_comp += x_dir * path_follow_compute_target_comp_cm(0.0f,
                                                         x_run_cm,
                                                         PATH_FOLLOW_TARGET_X_RUN_COMP_K);
    x_comp += y_dir * y_run_cm * PATH_FOLLOW_TARGET_X_FROM_Y_RUN_COMP_K;
    y_comp += y_dir * path_follow_compute_target_comp_cm(0.0f,
                                                         y_run_cm,
                                                         PATH_FOLLOW_TARGET_Y_RUN_COMP_K);

    if (x_comp_cm != NULL)
    {
        *x_comp_cm = x_comp;
    }
    if (y_comp_cm != NULL)
    {
        *y_comp_cm = y_comp;
    }
}

static void path_follow_get_compensated_target_position(size_t target_idx,
                                                        Position target,
                                                        float *target_x_m,
                                                        float *target_y_m)
{
    float x_comp_cm = 0.0f;
    float y_comp_cm = 0.0f;

    if (target_x_m == NULL || target_y_m == NULL)
    {
        return;
    }

    path_follow_get_segment_target_comp_cm(target_idx, &x_comp_cm, &y_comp_cm);

    *target_x_m = target.row * g_ctx.grid_m + x_comp_cm / 100.0f;
    *target_y_m = target.col * g_ctx.grid_m + y_comp_cm / 100.0f;
}

static void path_follow_commit_raw_target_pose(Position target)
{
    path_follow_get_raw_target_position(target,
                                        &g_ctx.pose.x_m,
                                        &g_ctx.pose.y_m);
}

/**
 * @brief 澶嶄綅 S 鏇茬嚎 band 閰嶇疆鍒伴粯璁ゅ€笺€?
 */
void path_follow_reset_scurve_band_defaults(void)
{
    uint8 i;

    for (i = 0U; i < PATH_FOLLOW_SCURVE_BAND_COUNT; ++i)
    {
        g_path_follow_scurve_band_cfg[i] = g_path_follow_scurve_band_default_cfg[i];
    }
}

/**
 * @brief 鏍℃瀵瑰鍙皟鐨?S 鏇茬嚎 band 閰嶇疆锛岄潪娉曞€煎洖閫€鍒伴粯璁ゅ€笺€?
 */
void path_follow_sanitize_scurve_band_cfg(void)
{
    uint8 i;

    for (i = 0U; i < PATH_FOLLOW_SCURVE_BAND_COUNT; ++i)
    {
        g_path_follow_scurve_band_cfg[i].distance_upper_m =
            g_path_follow_scurve_band_default_cfg[i].distance_upper_m;

        if (!(g_path_follow_scurve_band_cfg[i].vmax_mps > 0.0f))
        {
            g_path_follow_scurve_band_cfg[i].vmax_mps =
                g_path_follow_scurve_band_default_cfg[i].vmax_mps;
        }
        if (!(g_path_follow_scurve_band_cfg[i].amax_mps2 > 0.0f))
        {
            g_path_follow_scurve_band_cfg[i].amax_mps2 =
                g_path_follow_scurve_band_default_cfg[i].amax_mps2;
        }
        if (!(g_path_follow_scurve_band_cfg[i].jmax_mps3 > 0.0f))
        {
            g_path_follow_scurve_band_cfg[i].jmax_mps3 =
                g_path_follow_scurve_band_default_cfg[i].jmax_mps3;
        }
    }
}

/**
 * @brief 澶嶄綅褰撳墠璺緞娈甸攣瀹氱殑 S 鏇茬嚎 band 鍙傛暟銆?
 */
static void path_follow_reset_active_scurve_cfg(void)
{
    g_ctx.active_scurve_cfg.band_idx = PATH_FOLLOW_INVALID_SCURVE_BAND_IDX;
    g_ctx.active_scurve_cfg.max_speed_cmps = 0.0f;
    g_ctx.active_scurve_cfg.accel_cmpss = 0.0f;
    g_ctx.active_scurve_cfg.jerk_cmpsss = 0.0f;
}

/**
 * @brief 鏍规嵁娈甸暱閫夋嫨褰撳墠璺緞娈靛簲閿佸畾鐨?S 鏇茬嚎 band銆?
 *
 * @param distance_m 褰撳墠璺緞娈垫€婚暱搴︼紝鍗曚綅 m銆?
 * @param runtime_cfg 閫変腑鐨勮繍琛屽弬鏁拌緭鍑恒€?
 */
static void path_follow_select_scurve_band(float distance_m,
                                           path_follow_scurve_runtime_cfg_t *runtime_cfg)
{
    uint8 i;

    if (runtime_cfg == NULL)
    {
        return;
    }

    path_follow_sanitize_scurve_band_cfg();
    distance_m = fmaxf(distance_m, 0.0f);

    for (i = 0U; i < PATH_FOLLOW_SCURVE_BAND_COUNT; ++i)
    {
        if (distance_m <= g_path_follow_scurve_band_cfg[i].distance_upper_m)
        {
            runtime_cfg->band_idx = i;
            runtime_cfg->max_speed_cmps = path_follow_mps_to_cmps(g_path_follow_scurve_band_cfg[i].vmax_mps);
            runtime_cfg->accel_cmpss = path_follow_mps2_to_cmpss(g_path_follow_scurve_band_cfg[i].amax_mps2);
            runtime_cfg->jerk_cmpsss = path_follow_mps3_to_cmpsss(g_path_follow_scurve_band_cfg[i].jmax_mps3);
            return;
        }
    }

    runtime_cfg->band_idx = PATH_FOLLOW_SCURVE_BAND_COUNT - 1U;
    runtime_cfg->max_speed_cmps = path_follow_mps_to_cmps(g_path_follow_scurve_band_cfg[PATH_FOLLOW_SCURVE_BAND_COUNT - 1U].vmax_mps);
    runtime_cfg->accel_cmpss = path_follow_mps2_to_cmpss(g_path_follow_scurve_band_cfg[PATH_FOLLOW_SCURVE_BAND_COUNT - 1U].amax_mps2);
    runtime_cfg->jerk_cmpsss = path_follow_mps3_to_cmpsss(g_path_follow_scurve_band_cfg[PATH_FOLLOW_SCURVE_BAND_COUNT - 1U].jmax_mps3);
}

/**
 * @brief 鏍规嵁褰撳墠涓婁笅鏂囦腑鐨勬渶澶ч€熷害/瑙掗€熷害鏇存柊 PID 杈撳嚭闄愬箙銆?
 *
 * @note 褰撳墠涓婚摼璺湭涓诲姩璋冪敤璇ュ嚱鏁帮紝浣嗕繚鐣欏畠鐢ㄤ簬鍚庣画鍦ㄧ嚎璋冨弬鎴栨仮澶嶆棫鎺у埗鍣ㄦ椂澶嶇敤銆?
 */
static void path_follow_update_pid_limits(void)
{
    // 鎸?max_v/max_w 鏇存柊 PID 闄愬箙
    pid_world_init.fMax_Iout = g_ctx.max_v_mps * 100.0f;
    pid_world_init.fMax_Out = g_ctx.max_v_mps * 100.0f;
    PID_Update(&pid_world_x, &pid_world_init);
    PID_Update(&pid_world_y, &pid_world_init);

    pid_yaw_init.fMax_Iout = g_ctx.max_w_rad * 20.0f;
    pid_yaw_init.fMax_Out = g_ctx.max_w_rad * 20.0f;
    PID_Update(&pid_yaw, &pid_yaw_init);
}

static void path_follow_apply_runtime_tuning(void)
{
    if (path_corner_commit_lateral_gate_min_m < 0.001f)
    {
        path_corner_commit_lateral_gate_min_m = 0.001f;
    }
    if (path_hold_trim_release_distance < path_corner_commit_lateral_gate_min_m)
    {
        path_hold_trim_release_distance = path_corner_commit_lateral_gate_min_m;
    }
    if (path_line_guide_kp < 0.0f)
    {
        path_line_guide_kp = 0.0f;
    }
    if (path_follow_corner_hold_trim_scale < 0.0f)
    {
        path_follow_corner_hold_trim_scale = 0.0f;
    }
    if (path_line_guide_min_cmps < 0.0f)
    {
        path_line_guide_min_cmps = 0.0f;
    }
    if (path_line_guide_min_cmps > PATH_LINE_GUIDE_MAX_CMPS)
    {
        path_line_guide_min_cmps = PATH_LINE_GUIDE_MAX_CMPS;
    }
    if (path_corner_handover_commit_distance_m < 0.0f)
    {
        path_corner_handover_commit_distance_m = 0.0f;
    }
    if (path_corner_handover_enter_distance_m <=
        (path_corner_handover_commit_distance_m + PATH_CORNER_HANDOVER_WINDOW_GAP_MIN_M))
    {
        path_corner_handover_enter_distance_m =
            path_corner_handover_commit_distance_m + PATH_CORNER_HANDOVER_WINDOW_GAP_MIN_M;
    }
    path_follow_enable_corner_handover = path_follow_enable_corner_handover ? 1U : 0U;

    g_ctx.pos_tol_m = path_corner_commit_lateral_gate_min_m;
    g_ctx.speed_cfg.hold_release_distance_m = path_hold_trim_release_distance;
}

/**
 * @brief 涓哄崟鏉¤矾寰勬涓€娆℃€ф瀯閫犳爣鍑?7 娈?jerk-limited S 鏇茬嚎 profile銆?
 *
 * @param profile 杈撳嚭 profile銆?
 * @param distance_cm 褰撳墠璺緞娈垫€讳綅绉伙紝鍗曚綅 cm銆?
 * @param v0_cmps 璧峰閫熷害锛屽崟浣?cm/s銆?
 * @param v1_cmps 鏈閫熷害锛屽崟浣?cm/s銆?
 * @param v_max_cmps 鏈€澶ч€熷害绾︽潫锛屽崟浣?cm/s銆?
 * @param a_max_cmpss 鏈€澶у姞閫熷害绾︽潫锛屽崟浣?cm/s^2銆?
 * @param j_max_cmpsss 鏈€澶?jerk 绾︽潫锛屽崟浣?cm/s^3銆?
 * @return `1` 琛ㄧず鏋勯€犳垚鍔燂紝`0` 琛ㄧず鍦ㄧ粰瀹氳竟鐣屾潯浠跺拰绾︽潫涓嬪綋鍓嶆涓嶅彲琛屻€?
 */
static uint8 path_follow_build_scurve_profile(path_follow_scurve_profile_t *profile,
                                              float distance_cm,
                                              float v0_cmps,
                                              float v1_cmps,
                                              float v_max_cmps,
                                              float a_max_cmpss,
                                              float j_max_cmpsss)
{
    float T1;
    float T2;
    float Tjs;
    float Tj1;
    float Tj2;
    float Ta;
    float Td;
    float Tv;
    float Tj;
    float delta;
    float a_work;

    if (profile == NULL)
    {
        return 0U;
    }

    *profile = (path_follow_scurve_profile_t){0};

    if (distance_cm <= 0.0f ||
        v_max_cmps <= 0.0f ||
        a_max_cmpss <= 0.0f ||
        j_max_cmpsss <= 0.0f)
    {
        return 0U;
    }

    v0_cmps = fminf(fmaxf(v0_cmps, 0.0f), v_max_cmps);
    v1_cmps = fminf(fmaxf(v1_cmps, 0.0f), v_max_cmps);

    T1 = sqrtf(fabsf(v1_cmps - v0_cmps) / j_max_cmpsss);
    T2 = v_max_cmps / j_max_cmpsss;
    Tjs = fminf(T1, T2);

    if ((T1 <= T2 && distance_cm < (Tjs * (v0_cmps + v1_cmps))) ||
        (T1 > T2 && distance_cm < (0.5f * (v0_cmps + v1_cmps) *
                                   (Tjs + fabsf(v1_cmps - v0_cmps) / a_max_cmpss))))
    {
        return 0U;
    }

    if ((v_max_cmps - v0_cmps) * j_max_cmpsss < (a_max_cmpss * a_max_cmpss))
    {
        Tj1 = sqrtf(fmaxf(v_max_cmps - v0_cmps, 0.0f) / j_max_cmpsss);
        Ta = 2.0f * Tj1;
        profile->alima = j_max_cmpsss * Tj1;
    }
    else
    {
        Tj1 = a_max_cmpss / j_max_cmpsss;
        Ta = Tj1 + (v_max_cmps - v0_cmps) / a_max_cmpss;
        profile->alima = a_max_cmpss;
    }

    if ((v_max_cmps - v1_cmps) * j_max_cmpsss < (a_max_cmpss * a_max_cmpss))
    {
        Tj2 = sqrtf(fmaxf(v_max_cmps - v1_cmps, 0.0f) / j_max_cmpsss);
        Td = 2.0f * Tj2;
        profile->alimd = j_max_cmpsss * Tj2;
    }
    else
    {
        Tj2 = a_max_cmpss / j_max_cmpsss;
        Td = Tj2 + (v_max_cmps - v1_cmps) / a_max_cmpss;
        profile->alimd = a_max_cmpss;
    }

    Tv = distance_cm / v_max_cmps -
         Ta * 0.5f * (1.0f + v0_cmps / v_max_cmps) -
         Td * 0.5f * (1.0f + v1_cmps / v_max_cmps);
    if (Tv > 0.0f)
    {
        profile->s = distance_cm;
        profile->x0 = 0.0f;
        profile->x1 = distance_cm;
        profile->v0 = v0_cmps;
        profile->v1 = v1_cmps;
        profile->vmax = v_max_cmps;
        profile->amax = a_max_cmpss;
        profile->jmax = j_max_cmpsss;
        profile->vlim = v_max_cmps;
        profile->Tj1 = Tj1;
        profile->Tj2 = Tj2;
        profile->Ta = Ta;
        profile->Td = Td;
        profile->Tv = Tv;
        profile->T = Ta + Tv + Td;
        profile->valid = 1U;
        return 1U;
    }

    Tv = 0.0f;
    Tj = a_max_cmpss / j_max_cmpsss;
    Tj1 = Tj;
    Tj2 = Tj;
    delta = powf(a_max_cmpss, 4) / powf(j_max_cmpsss, 2) +
            2.0f * (v0_cmps * v0_cmps + v1_cmps * v1_cmps) +
            a_max_cmpss * (4.0f * distance_cm -
                           2.0f * a_max_cmpss / j_max_cmpsss * (v0_cmps + v1_cmps));
    delta = fmaxf(delta, 0.0f);
    Ta = (powf(a_max_cmpss, 2) / j_max_cmpsss - 2.0f * v0_cmps + sqrtf(delta)) /
         (2.0f * a_max_cmpss);
    Td = (powf(a_max_cmpss, 2) / j_max_cmpsss - 2.0f * v1_cmps + sqrtf(delta)) /
         (2.0f * a_max_cmpss);
    if (Ta > 2.0f * Tj && Td > 2.0f * Tj)
    {
        profile->s = distance_cm;
        profile->x0 = 0.0f;
        profile->x1 = distance_cm;
        profile->v0 = v0_cmps;
        profile->v1 = v1_cmps;
        profile->vmax = v_max_cmps;
        profile->amax = a_max_cmpss;
        profile->jmax = j_max_cmpsss;
        profile->Tj1 = Tj1;
        profile->Tj2 = Tj2;
        profile->Ta = Ta;
        profile->Td = Td;
        profile->Tv = Tv;
        profile->T = Ta + Td;
        profile->alima = a_max_cmpss;
        profile->alimd = a_max_cmpss;
        profile->vlim = v0_cmps + (Ta - Tj1) * profile->alima;
        profile->valid = 1U;
        return 1U;
    }

    a_work = a_max_cmpss;
    while (Ta < 2.0f * Tj || Td < 2.0f * Tj)
    {
        if (Ta > 0.0f && Td > 0.0f)
        {
            a_work *= 0.99f;
            if (a_work <= 0.0f)
            {
                return 0U;
            }

            Tj = a_work / j_max_cmpsss;
            Tj1 = Tj;
            Tj2 = Tj;
            delta = powf(a_work, 4) / powf(j_max_cmpsss, 2) +
                    2.0f * (v0_cmps * v0_cmps + v1_cmps * v1_cmps) +
                    a_work * (4.0f * distance_cm -
                              2.0f * a_work / j_max_cmpsss * (v0_cmps + v1_cmps));
            delta = fmaxf(delta, 0.0f);
            Ta = (powf(a_work, 2) / j_max_cmpsss - 2.0f * v0_cmps + sqrtf(delta)) /
                 (2.0f * a_work);
            Td = (powf(a_work, 2) / j_max_cmpsss - 2.0f * v1_cmps + sqrtf(delta)) /
                 (2.0f * a_work);
            continue;
        }

        if ((v0_cmps + v1_cmps) <= 0.0f)
        {
            return 0U;
        }

        if (Ta <= 0.0f)
        {
            float numer;
            float denom;
            Ta = 0.0f;
            Tj1 = 0.0f;
            Td = 2.0f * distance_cm / (v0_cmps + v1_cmps);
            numer = j_max_cmpsss * distance_cm -
                    sqrtf(fmaxf(j_max_cmpsss * (j_max_cmpsss * distance_cm * distance_cm +
                                                (v1_cmps + v0_cmps) * (v1_cmps + v0_cmps) *
                                                (v1_cmps - v0_cmps)),
                                0.0f));
            denom = j_max_cmpsss * (v1_cmps + v0_cmps);
            if (fabsf(denom) <= 1e-6f)
            {
                return 0U;
            }
            Tj2 = numer / denom;
        }
        else
        {
            float numer;
            float denom;
            Td = 0.0f;
            Tj2 = 0.0f;
            Ta = 2.0f * distance_cm / (v0_cmps + v1_cmps);
            numer = j_max_cmpsss * distance_cm -
                    sqrtf(fmaxf(j_max_cmpsss * (j_max_cmpsss * distance_cm * distance_cm -
                                                (v1_cmps + v0_cmps) * (v1_cmps + v0_cmps) *
                                                (v1_cmps - v0_cmps)),
                                0.0f));
            denom = j_max_cmpsss * (v1_cmps + v0_cmps);
            if (fabsf(denom) <= 1e-6f)
            {
                return 0U;
            }
            Tj1 = numer / denom;
        }

        profile->s = distance_cm;
        profile->x0 = 0.0f;
        profile->x1 = distance_cm;
        profile->v0 = v0_cmps;
        profile->v1 = v1_cmps;
        profile->vmax = v_max_cmps;
        profile->amax = a_work;
        profile->jmax = j_max_cmpsss;
        profile->Tj1 = Tj1;
        profile->Tj2 = Tj2;
        profile->Ta = Ta;
        profile->Td = Td;
        profile->Tv = 0.0f;
        profile->T = Ta + Td;
        profile->alima = j_max_cmpsss * Tj1;
        profile->alimd = j_max_cmpsss * Tj2;
        profile->vlim = v0_cmps + (Ta - Tj1) * profile->alima;
        profile->valid = 1U;
        return 1U;
    }

    profile->s = distance_cm;
    profile->x0 = 0.0f;
    profile->x1 = distance_cm;
    profile->v0 = v0_cmps;
    profile->v1 = v1_cmps;
    profile->vmax = v_max_cmps;
    profile->amax = a_work;
    profile->jmax = j_max_cmpsss;
    profile->Tj1 = Tj1;
    profile->Tj2 = Tj2;
    profile->Ta = Ta;
    profile->Td = Td;
    profile->Tv = 0.0f;
    profile->T = Ta + Td;
    profile->alima = j_max_cmpsss * Tj1;
    profile->alimd = j_max_cmpsss * Tj2;
    profile->vlim = v0_cmps + (Ta - Tj1) * profile->alima;
    profile->valid = 1U;
    return 1U;
}

static uint8 path_follow_target_requires_pause(size_t target_idx);
static uint8 path_follow_is_route_corner_target(void);
#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER || PATH_FOLLOW_ENABLE_LINE_GUIDE
static uint8 path_follow_get_segment_points(const Position **prev_point,
                                            const Position **curr_point,
                                            const Position **next_point);
static uint8 path_follow_compute_segment_progress_m(const pose2d_t *pose,
                                                    const Position *seg_start,
                                                    const Position *seg_end,
                                                    float *progress_m,
                                                    float *segment_length_m,
                                                    float *normal_error_m);
#endif
#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER
static void path_follow_reset_corner_handover_state(void);
#endif
#if PATH_FOLLOW_ENABLE_LINE_GUIDE
static uint8 path_follow_apply_line_guidance(float ref_speed_cmps,
                                             float *vx_world_cmps,
                                             float *vy_world_cmps);
#endif

/**
 * @brief 鎸夊綋鍓嶈矾寰勬鐨勭疮璁℃墽琛屾椂闂撮噰鏍锋爣鍑?S 鏇茬嚎鐩爣閫熷害銆?
 *
 * @param t_s 浠庡綋鍓?profile 璧风偣寮€濮嬬疮璁＄殑鍏ㄥ眬鏃堕棿锛屽崟浣?s銆?
 * @param profile 鐢?`path_follow_build_scurve_profile()` 鏋勯€犵殑 profile銆?
 * @return 褰撳墠閲囨牱鏃跺埢鐨勭洰鏍囬€熷害锛屽崟浣?cm/s銆?
 */
static float path_follow_sample_scurve_velocity(float t_s,
                                                const path_follow_scurve_profile_t *profile)
{
    if (profile == NULL || !profile->valid)
    {
        return 0.0f;
    }
    if (t_s <= 0.0f)
    {
        return profile->v0;
    }
    if (t_s >= profile->T)
    {
        return profile->v1;
    }

    if (t_s < profile->Tj1)
    {
        return profile->v0 + profile->jmax * t_s * t_s * 0.5f;
    }
    if (t_s < (profile->Ta - profile->Tj1))
    {
        return profile->v0 + profile->alima * (t_s - profile->Tj1 * 0.5f);
    }
    if (t_s < profile->Ta)
    {
        float dt = profile->Ta - t_s;
        return profile->vlim - profile->jmax * dt * dt * 0.5f;
    }
    if (t_s < (profile->Ta + profile->Tv))
    {
        return profile->vlim;
    }
    if (t_s < (profile->T - profile->Td + profile->Tj2))
    {
        float dt = t_s - profile->T + profile->Td;
        return profile->vlim - profile->jmax * dt * dt * 0.5f;
    }
    if (t_s < (profile->T - profile->Tj2))
    {
        return profile->vlim - profile->alimd *
               (t_s - profile->T + profile->Td - profile->Tj2 * 0.5f);
    }

    {
        float dt = profile->T - t_s;
        return profile->v1 + profile->jmax * dt * dt * 0.5f;
    }
}

#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER || PATH_FOLLOW_ENABLE_LINE_GUIDE
static uint8 path_follow_compute_segment_progress_xy_m(const pose2d_t *pose,
                                                       float start_x_m,
                                                       float start_y_m,
                                                       float end_x_m,
                                                       float end_y_m,
                                                       float *progress_m,
                                                       float *segment_length_m,
                                                       float *normal_error_m)
{
    float seg_dx_m;
    float seg_dy_m;
    float seg_norm_m;
    float seg_dir_x;
    float seg_dir_y;
    float rel_x_m;
    float rel_y_m;

    if (progress_m != NULL)
    {
        *progress_m = 0.0f;
    }
    if (segment_length_m != NULL)
    {
        *segment_length_m = 0.0f;
    }
    if (normal_error_m != NULL)
    {
        *normal_error_m = 0.0f;
    }

    if (pose == NULL || progress_m == NULL ||
        segment_length_m == NULL || normal_error_m == NULL)
    {
        return 0U;
    }

    seg_dx_m = end_x_m - start_x_m;
    seg_dy_m = end_y_m - start_y_m;
    seg_norm_m = sqrtf(seg_dx_m * seg_dx_m + seg_dy_m * seg_dy_m);
    if (seg_norm_m <= 1e-6f)
    {
        return 0U;
    }

    seg_dir_x = seg_dx_m / seg_norm_m;
    seg_dir_y = seg_dy_m / seg_norm_m;
    rel_x_m = pose->x_m - start_x_m;
    rel_y_m = pose->y_m - start_y_m;

    *progress_m = rel_x_m * seg_dir_x + rel_y_m * seg_dir_y;
    *segment_length_m = seg_norm_m;
    *normal_error_m = rel_x_m * (-seg_dir_y) + rel_y_m * seg_dir_x;
    return 1U;
}

/**
 * @brief 鑾峰彇褰撳墠鐩爣鐩稿叧鐨勫墠涓€瑙掔偣銆佸綋鍓嶈鐐瑰拰鍚庝竴瑙掔偣銆?
 *
 * @note 鑻ユ煇涓€渚т笉瀛樺湪锛屽搴旇緭鍑轰細琚疆涓?NULL銆?
 *
 * @param prev_point 鍓嶄竴瑙掔偣杈撳嚭銆?
 * @param curr_point 褰撳墠鐩爣瑙掔偣杈撳嚭銆?
 * @param next_point 鍚庝竴瑙掔偣杈撳嚭銆?
 * @return `1` 琛ㄧず褰撳墠鑷冲皯瀛樺湪鏈夋晥 curr_point锛宍0` 琛ㄧず褰撳墠璺緞涓婁笅鏂囨棤鏁堛€?
 */
static uint8 path_follow_get_segment_points(const Position **prev_point,
                                            const Position **curr_point,
                                            const Position **next_point)
{
    if (prev_point != NULL)
    {
        *prev_point = NULL;
    }
    if (curr_point != NULL)
    {
        *curr_point = NULL;
    }
    if (next_point != NULL)
    {
        *next_point = NULL;
    }

    if (g_ctx.path == NULL || g_ctx.idx >= g_ctx.steps)
    {
        return 0U;
    }

    if (prev_point != NULL && g_ctx.idx > 0U)
    {
        *prev_point = &g_ctx.path[g_ctx.idx - 1U];
    }
    if (curr_point != NULL)
    {
        *curr_point = &g_ctx.path[g_ctx.idx];
    }
    if (next_point != NULL && (g_ctx.idx + 1U) < g_ctx.steps)
    {
        *next_point = &g_ctx.path[g_ctx.idx + 1U];
    }

    return 1U;
}

/**
 * @brief 璁＄畻褰撳墠浣嶇疆鍦?prev->curr 娈典笂鐨勬姇褰辫繘搴︺€佹闀垮拰妯悜璇樊銆?
 *
 * @param pose 褰撳墠浣嶅Э銆?
 * @param seg_start 褰撳墠娈佃捣鐐?prev銆?
 * @param seg_end 褰撳墠娈电粓鐐?curr銆?
 * @param progress_m 杈撳嚭褰撳墠鎶曞奖杩涘害 s锛屽崟浣?m銆?
 * @param segment_length_m 杈撳嚭褰撳墠娈甸暱搴?L锛屽崟浣?m銆?
 * @param normal_error_m 杈撳嚭褰撳墠妯悜璇樊 e_n锛屽崟浣?m銆?
 * @return `1` 琛ㄧず璁＄畻鎴愬姛锛宍0` 琛ㄧず杈撳叆闈炴硶鎴栨闀块€€鍖栥€?
 */
static uint8 path_follow_compute_segment_progress_m(const pose2d_t *pose,
                                                    const Position *seg_start,
                                                    const Position *seg_end,
                                                    float *progress_m,
                                                    float *segment_length_m,
                                                    float *normal_error_m)
{
    float start_x_m;
    float start_y_m;
    float end_x_m;
    float end_y_m;
    float seg_dx_m;
    float seg_dy_m;
    float seg_norm_m;
    float seg_dir_x;
    float seg_dir_y;
    float rel_x_m;
    float rel_y_m;

    if (progress_m != NULL)
    {
        *progress_m = 0.0f;
    }
    if (segment_length_m != NULL)
    {
        *segment_length_m = 0.0f;
    }
    if (normal_error_m != NULL)
    {
        *normal_error_m = 0.0f;
    }

    if (pose == NULL || seg_start == NULL || seg_end == NULL ||
        progress_m == NULL || segment_length_m == NULL || normal_error_m == NULL)
    {
        return 0U;
    }

    start_x_m = seg_start->row * g_ctx.grid_m;
    start_y_m = seg_start->col * g_ctx.grid_m;
    end_x_m = seg_end->row * g_ctx.grid_m;
    end_y_m = seg_end->col * g_ctx.grid_m;
    seg_dx_m = end_x_m - start_x_m;
    seg_dy_m = end_y_m - start_y_m;
    seg_norm_m = sqrtf(seg_dx_m * seg_dx_m + seg_dy_m * seg_dy_m);
    if (seg_norm_m <= 1e-6f)
    {
        return 0U;
    }

    seg_dir_x = seg_dx_m / seg_norm_m;
    seg_dir_y = seg_dy_m / seg_norm_m;
    rel_x_m = pose->x_m - start_x_m;
    rel_y_m = pose->y_m - start_y_m;

    *progress_m = rel_x_m * seg_dir_x + rel_y_m * seg_dir_y;
    *segment_length_m = seg_norm_m;
    *normal_error_m = rel_x_m * (-seg_dir_y) + rel_y_m * seg_dir_x;
    return 1U;
}
#endif

#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER
/**
 * @brief 鏍规嵁鍓嶅悗娈佃緝鐭暱搴﹁绠楄繘鍏?handover 鐨勮窛绂婚槇鍊笺€?
 *
 * @param prev_length_m 鍓嶄竴娈甸暱搴︼紝鍗曚綅 m銆?
 * @param next_length_m 鍚庝竴娈甸暱搴︼紝鍗曚綅 m銆?
 * @return 寤鸿鐨?handover 杩涘叆璺濈锛屽崟浣?m銆?
 */

#endif

/**
 * @brief 璁＄畻褰撳墠璺緞娈垫湯绔笇鏈涗繚鐣欑殑杩囨浮閫熷害銆?
 *
 * @return 褰撳墠娈垫湯绔洰鏍囬€熷害锛屽崟浣?cm/s銆?
 */
static float path_follow_compute_segment_end_speed(void)
{
    if ((g_ctx.idx + 1U) >= g_ctx.steps)
    {
        return 0.0f;
    }
    if (path_follow_target_requires_pause(g_ctx.idx))
    {
        return 0.0f;
    }



    return g_ctx.speed_cfg.segment_end_speed_cmps;
}

/**
 * @brief 鏍规嵁褰撳墠鍓╀綑璺濈璁＄畻涓€涓粎鐢ㄤ簬寮傚父淇濇姢鐨勫畨鍏ㄩ€熷害涓婇檺銆?
 *
 * @param distance_m 褰撳墠娈靛墿浣欒窛绂伙紝鍗曚綅 m銆?
 * @param end_speed_cmps 褰撳墠娈垫湯绔洰鏍囬€熷害锛屽崟浣?cm/s銆?
 * @param max_speed_cmps 褰撳墠璺緞娈甸攣瀹氱殑鏈€澶ч€熷害锛屽崟浣?cm/s銆?
 * @param accel_cmpss 褰撳墠璺緞娈甸攣瀹氱殑鏈€澶у姞閫熷害锛屽崟浣?cm/s^2銆?
 * @return 鎸夋渶澶у姞閫熷害绾︽潫鎹㈢畻寰楀埌鐨勫畨鍏ㄩ€熷害涓婇檺锛屽崟浣?cm/s銆?
 */
static float path_follow_compute_brake_speed_cap(float distance_m,
                                                 float end_speed_cmps,
                                                 float max_speed_cmps,
                                                 float accel_cmpss)
{
    float distance_cm = fmaxf(distance_m, 0.0f) * 100.0f;
    accel_cmpss = fmaxf(accel_cmpss, 1.0f);
    float speed_sq = end_speed_cmps * end_speed_cmps +
                     2.0f * accel_cmpss * distance_cm;

    return fminf(max_speed_cmps,
                 sqrtf(fmaxf(speed_sq, 0.0f)));
}

/**
 * @brief 褰?profile 鏋勯€犲け璐ユ椂锛岀敤鍗曟媿鍔犻€熷害闄愬箙鐢熸垚淇濆畧閫熷害浣滀负寮傚父淇濇姢銆?
 *
 * @param current_speed_cmps 褰撳墠鍙傝€冮€熷害锛屽崟浣?cm/s銆?
 * @param safety_speed_cmps 褰撳墠鍏佽鐨勫畨鍏ㄩ€熷害涓婇檺锛屽崟浣?cm/s銆?
 * @param accel_cmpss 褰撳墠璺緞娈甸攣瀹氱殑鏈€澶у姞閫熷害锛屽崟浣?cm/s^2銆?
 * @return 涓嬩竴鎷嶇殑閫熷害鍙傝€冿紝鍗曚綅 cm/s銆?
 */
static float path_follow_compute_profile_fault_speed(float current_speed_cmps,
                                                     float safety_speed_cmps,
                                                     float accel_cmpss)
{
    float accel_step = fmaxf(accel_cmpss, 1.0f) / (float)PID_RATE;

    if (current_speed_cmps < safety_speed_cmps)
    {
        current_speed_cmps += accel_step;
        if (current_speed_cmps > safety_speed_cmps)
        {
            current_speed_cmps = safety_speed_cmps;
        }
    }
    else
    {
        current_speed_cmps -= accel_step;
        if (current_speed_cmps < safety_speed_cmps)
        {
            current_speed_cmps = safety_speed_cmps;
        }
    }

    return fmaxf(current_speed_cmps, 0.0f);
}

/**
 * @brief 娓呯┖瀵瑰鍙鐨勮皟璇曠姸鎬佺紦瀛樸€?
 *
 * @note 璇ュ嚱鏁颁笉浼氬奖鍝嶈矾寰勩€佷綅濮垮拰 PID锛屼粎娓呴櫎鐘舵€佹煡璇笌灞忔樉鐢ㄧ殑璋冭瘯閲忋€?
 */
static void path_follow_clear_debug_state(void)
{
    g_ctx.debug.distance_m = 0.0f;
    g_ctx.debug.dir_x = 0.0f;
    g_ctx.debug.dir_y = 0.0f;
    g_ctx.debug.speed_ref_cmps = 0.0f;
    g_ctx.debug.target_yaw_deg = 0.0f;
    g_ctx.debug.vx_world_cmps = 0.0f;
    g_ctx.debug.vy_world_cmps = 0.0f;
    g_ctx.debug.segment_axis = 0U;
}

#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER
/**
 * @brief 娓呯┖鏅€氫腑闂存嫄鐐?handover 鐨勮繍琛屾€佺紦瀛樸€?
 */
static void path_follow_reset_corner_handover_state(void)
{
    g_ctx.corner_handover_active = 0U;
    g_ctx.corner_handover_idx = SIZE_MAX;
    g_ctx.corner_enter_distance_m = 0.0f;
    g_ctx.corner_commit_distance_m = 0.0f;
}
#endif

/**
 * @brief 浣垮綋鍓嶈矾寰勬鐨?S 鏇茬嚎 profile 澶辨晥锛屼絾淇濈暀涓婁竴鎷嶉€熷害鍙傝€冦€?
 */
static void path_follow_invalidate_active_profile(void)
{
    g_ctx.active_profile = (path_follow_scurve_profile_t){0};
    g_ctx.profile_time_s = 0.0f;
    g_ctx.profile_target_idx = 0U;
    g_ctx.profile_active = 0U;
}

/**
 * @brief 澶嶄綅鏁存寮?S 鏇茬嚎鎵ц鐘舵€併€?
 */
static void path_follow_reset_motion_profile_state(void)
{
    path_follow_invalidate_active_profile();
#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER
    path_follow_reset_corner_handover_state();
#endif
    path_follow_reset_active_scurve_cfg();
    g_ctx.last_ref_speed_cmps = 0.0f;
}

/**
 * @brief 灏?`pid_stay` 鐨勫弬鏁板悓姝ュ埌 `pid_stay_y`銆?
 *
 * @note 涓や釜 PID 浣跨敤鐩稿悓鍙傛暟锛屼絾淇濇寔鍚勮嚜鐙珛鐨勫唴閮ㄥ巻鍙茬姸鎬併€?
 */
static void path_follow_sync_stay_pid_gains(void)
{
    pid_stay_y.fKp = pid_stay.fKp;
    pid_stay_y.fKi = pid_stay.fKi;
    pid_stay_y.fKd = pid_stay.fKd;
    pid_stay_y.fMax_Iout = pid_stay.fMax_Iout;
    pid_stay_y.fMax_Out = pid_stay.fMax_Out;
    pid_stay_y.alpha = pid_stay.alpha;
}


/**
 * @brief 娓呯┖鏈ā鍧楀唴閮ㄦ帶鍒剁姸鎬併€?
 *
 * 璇ュ嚱鏁颁細娓呴櫎褰撳墠娈?S 鏇茬嚎 profile銆佽皟璇曠姸鎬佷互鍙婂钩绉讳綅缃浉鍏?PID 鐨勫巻鍙查噺锛?
 * 鐢ㄤ簬鏂拌矾寰勮杞姐€佷綅濮块噸缃垨鏁存潯璺緞缁撴潫绛夐渶瑕侀噸鏂拌捣鎺х殑鍦烘櫙銆?
 */
static void path_follow_reset_control_state(void)
{
    path_follow_reset_motion_profile_state();
    path_follow_clear_debug_state();
    PID_Clear(&pid_world_x);
    PID_Clear(&pid_world_y);
    PID_Clear(&pid_stay);
    PID_Clear(&pid_stay_y);
    //PID_Clear(&pid_yaw);
    //PID_Clear(&pid_accel_yaw);
}

static uint8 path_follow_finish_path(path_follow_output_t *out);

/**
 * @brief 澶嶄綅鏆傚仠浜嬩欢鐨勮繍琛屾€侊紝涓嶆竻闄ら厤缃〃鏈韩銆?
 *
 * @note 鏂拌矾寰勮杞姐€佷复鏃惰矾寰勫垏鎹互鍙婃仮澶嶅埌鏅€氳窡闅忓墠锛岄兘闇€瑕佹妸娓告爣鍜屽墿浣欏€掕鏃舵竻闆躲€?
 */
static void path_follow_reset_pause_runtime(void)
{
    g_ctx.pause_cursor = 0U;
    g_ctx.pause_cycles_remaining = 0U;
    g_ctx.paused = 0U;
}

/**
 * @brief 娓呯┖鏆傚仠浜嬩欢閰嶇疆鍙婂叾杩愯鎬併€?
 */
static void path_follow_clear_pause_config(void)
{
    size_t i;

    for (i = 0U; i < PATH_FOLLOW_MAX_PAUSE_POINTS; ++i)
    {
        g_ctx.pause_indices[i] = SIZE_MAX;
    }
    g_ctx.pause_count = 0U;
    g_ctx.pause_cycles_cfg = 0U;
    path_follow_reset_pause_runtime();
}

/**
 * @brief 灏嗘殏鍋滄父鏍囪拷璧跺埌褰撳墠鐩爣绱㈠紩锛岃烦杩囧凡缁忚繃鍘荤殑鏃т簨浠躲€?
 *
 * @param current_idx 褰撳墠璺緞鐩爣绱㈠紩銆?
 */
static void path_follow_sync_pause_cursor(size_t current_idx)
{
    while (g_ctx.pause_cursor < g_ctx.pause_count &&
           g_ctx.pause_indices[g_ctx.pause_cursor] < current_idx)
    {
        g_ctx.pause_cursor++;
    }
}

/**
 * @brief 鍒ゆ柇褰撳墠鐩爣 corner 鏄惁闇€瑕佸湪鍒扮偣鍚庢殏鍋溿€?
 *
 * @param target_idx 褰撳墠鐩爣 corner 绱㈠紩銆?
 * @return `1` 琛ㄧず璇?target_idx 鏄笅涓€涓緟瑙﹀彂鏆傚仠鐐癸紝`0` 琛ㄧず涓嶆槸銆?
 */
static uint8 path_follow_target_requires_pause(size_t target_idx)
{
    if (!g_ctx.pause_events_enabled || g_ctx.paused || 0U == g_ctx.pause_cycles_cfg)
    {
        return 0U;
    }

    path_follow_sync_pause_cursor(target_idx);
    if (g_ctx.pause_cursor >= g_ctx.pause_count)
    {
        return 0U;
    }

    return (g_ctx.pause_indices[g_ctx.pause_cursor] == target_idx) ? 1U : 0U;
}

/**
 * @brief 杩涘叆涓€涓€滃埌鐐瑰悗闈欐绛夊緟鈥濈殑鏆傚仠绐楀彛銆?
 *
 * @param target_idx 褰撳墠瑙﹀彂鏆傚仠鐨?corner 绱㈠紩锛屼粎鐢ㄤ簬璋冭瘯璇箟淇濇寔銆?
 */
static void path_follow_enter_pause(size_t target_idx)
{
    (void)target_idx;

    g_ctx.paused = 1U;
    g_ctx.pause_cycles_remaining = (g_ctx.pause_cycles_cfg > 0U) ? g_ctx.pause_cycles_cfg : 1U;
    car_direction = 0U;
    /* Pause resumes with a fresh segment profile, so clear the current motion state here. */
    path_follow_reset_control_state();
}

/**
 * @brief 澶勭悊鏆傚仠绐楀彛鐨勫€掕鏃朵笌鎭㈠閫昏緫銆?
 *
 * @param out 杈撳嚭缁撴瀯浣撱€傛殏鍋滄湡闂翠繚鎸?active=1 涓斾笁杞撮€熷害涓?0銆?
 * @return `1` 琛ㄧず鏈懆鏈熷凡鐢辨殏鍋滈€昏緫瀹屽叏澶勭悊锛宍0` 琛ㄧず褰撳墠涓嶅湪鏆傚仠鎬併€?
 */
static uint8 path_follow_handle_pause(path_follow_output_t *out)
{
    if (!g_ctx.paused)
    {
        return 0U;
    }

    car_direction = 0U;
    path_follow_clear_debug_state();

    if (out != NULL)
    {
        out->active = 1U;
        out->reached = 0U;
        out->vx_cmd = 0.0f;
        out->vy_cmd = 0.0f;
        out->omega_cmd = 0.0f;
        out->target_idx = g_ctx.idx;
    }

    if (g_ctx.pause_cycles_remaining > 0U)
    {
        g_ctx.pause_cycles_remaining--;
    }
    if (g_ctx.pause_cycles_remaining > 0U)
    {
        return 1U;
    }

    g_ctx.paused = 0U;
    if (g_ctx.pause_cursor < g_ctx.pause_count &&
        g_ctx.pause_indices[g_ctx.pause_cursor] == g_ctx.idx)
    {
        g_ctx.pause_cursor++;
    }

    if ((g_ctx.idx + 1U) < g_ctx.steps)
    {
        g_ctx.idx++;
        /* The next segment must rebuild its own profile from standstill after pause release. */
        path_follow_reset_control_state();
        return 1U;
    }

    (void)path_follow_finish_path(out);
    if (out != NULL)
    {
        out->active = 0U;
        out->target_idx = g_ctx.idx;
    }
    return 1U;
}

/**
 * @brief 瑁呰浇涓€鏉℃柊鐨勮矾寰勫埌璺緞璺熼殢涓婁笅鏂囥€?
 *
 * 璇ュ嚱鏁拌礋璐ｇ粺涓€澶勭悊璺緞鍒囨崲鏃剁殑鐘舵€侀噸缃€佺綉鏍煎垎杈ㄧ巼鍒囨崲銆?
 * 璧风偣閲嶇疆浠ュ強棣栫洰鏍囩偣璺宠繃绛栫暐銆?
 *
 * @param path 璺緞鐐规暟缁勬寚閽堛€?
 * @param steps 璺緞鐐规暟閲忋€?
 * @param grid_m 璺緞瀵瑰簲缃戞牸杈归暱锛屽崟浣?m銆?
 * @param reset_pose_to_first 鏄惁灏嗗綋鍓嶄綅濮块噸缃埌璺緞棣栫偣銆?
 * @param skip_first_target 鏄惁璺宠繃璺緞棣栫偣锛岀洿鎺ヨ窡闅忎笅涓€鐩爣鐐广€?
 * @param pause_events_enabled 璇ヨ矾寰勬槸鍚﹀厑璁歌Е鍙戦閰嶇疆鐨勬殏鍋滀簨浠躲€?
 */
static void path_follow_apply_path(const Position *path,
                                   size_t steps,
                                   float grid_m,
                                   uint8 reset_pose_to_first,
                                   uint8 skip_first_target,
                                   uint8 pause_events_enabled)
{
    path_follow_reset_control_state();
    path_follow_reset_pause_runtime();
    g_ctx.path = path;
    g_ctx.steps = steps;
    g_ctx.grid_m = (grid_m > 0.0f) ? grid_m : g_ctx.default_grid_m;
    g_ctx.idx = 0;
    g_ctx.pause_events_enabled = pause_events_enabled;
    g_ctx.rotate_only_active = 0U;

    if (path && steps > 0U)
    {
        if (reset_pose_to_first)
        {
            g_ctx.pose.x_m = path[0].row * g_ctx.grid_m;
            g_ctx.pose.y_m = path[0].col * g_ctx.grid_m;
        }

        if (skip_first_target && steps > 1U)
        {
            g_ctx.idx = 1U;
        }

        g_ctx.active = 1U;
    }
    else
    {
        g_ctx.active = 0U;
    }
}

/**
 * @brief 鐢熸垚涓€鏉″彧鍖呭惈姘村钩/绔栫洿涓ゆ鐨勪复鏃惰矾寰勫苟鍚姩璺熼殢銆?
 *
 * 璇ュ嚱鏁颁富瑕佺敤浜庡彂杞﹀墠鍥哄畾鍋忕Щ鍜屽閮ㄤ綅濮夸慨姝ｅ満鏅紝
 * 浼氳嚜鍔ㄦ牴鎹綅绉绘柟鍚戝喅瀹氬厛璧?X 杩樻槸鍏堣蛋 Y銆?
 *
 * @param target_x_m 涓存椂鐩爣鐐?X 鍧愭爣锛屽崟浣?m銆?
 * @param target_y_m 涓存椂鐩爣鐐?Y 鍧愭爣锛屽崟浣?m銆?
 * @param path_buffer 涓存椂璺緞缂撳瓨銆?
 * @param buffer_capacity 璺緞缂撳瓨瀹归噺銆?
 * @param grid_m 鐢熸垚涓存椂璺緞鏃朵娇鐢ㄧ殑鏍呮牸鍒嗚鲸鐜囷紝鍗曚綅 m銆?
 */
static void path_follow_start_axis_move(float target_x_m,
                                        float target_y_m,
                                        Position *path_buffer,
                                        size_t buffer_capacity,
                                        float grid_m)
{
    const float eps_m = 0.001f;
    float start_x_m = g_ctx.pose.x_m;
    float start_y_m = g_ctx.pose.y_m;
    float delta_x_m = target_x_m - start_x_m;
    float delta_y_m = target_y_m - start_y_m;
    uint8 move_x_first = (fabsf(delta_x_m) >= fabsf(delta_y_m)) ? 1U : 0U;
    size_t steps = 1U;

    if (path_buffer == NULL || buffer_capacity < 3U)
    {
        return;
    }

    if (fabsf(delta_x_m) <= eps_m && fabsf(delta_y_m) <= eps_m)
    {
        path_follow_apply_path(NULL, 0U, grid_m, 0U, 0U, 0U);
        return;
    }

    path_buffer[0].row = (int)lroundf(start_x_m / grid_m);
    path_buffer[0].col = (int)lroundf(start_y_m / grid_m);

    if (move_x_first)
    {
        if (fabsf(delta_x_m) > eps_m)
        {
            path_buffer[steps].row = (int)lroundf(target_x_m / grid_m);
            path_buffer[steps].col = (int)lroundf(start_y_m / grid_m);
            steps++;
        }

        if (fabsf(delta_y_m) > eps_m)
        {
            path_buffer[steps].row = (int)lroundf(target_x_m / grid_m);
            path_buffer[steps].col = (int)lroundf(target_y_m / grid_m);
            steps++;
        }
    }
    else
    {
        if (fabsf(delta_y_m) > eps_m)
        {
            path_buffer[steps].row = (int)lroundf(start_x_m / grid_m);
            path_buffer[steps].col = (int)lroundf(target_y_m / grid_m);
            steps++;
        }

        if (fabsf(delta_x_m) > eps_m)
        {
            path_buffer[steps].row = (int)lroundf(target_x_m / grid_m);
            path_buffer[steps].col = (int)lroundf(target_y_m / grid_m);
            steps++;
        }
    }

    path_follow_apply_path(path_buffer, steps, grid_m, 0U, 1U, 0U);
}

/**
 * @brief 鍒濆鍖栬矾寰勮窡闅忔ā鍧椼€?
 *
 * 璇ュ嚱鏁板畬鎴愪笂涓嬫枃榛樿鍊笺€侀€熷害瑙勫垝鍙傛暟浠ュ強鐩稿叧 PID 鐨勫垵濮嬪寲銆?
 *
 * @param grid_size_m 榛樿璺緞缃戞牸杈归暱锛屽崟浣?m銆?
 * @param pulses_per_meter 缂栫爜鍣ㄦ瘡绫宠剦鍐叉暟锛岀敤浜庨噷绋嬭鎹㈢畻銆?
 */
void path_follow_init(float grid_size_m, float pulses_per_meter)
{
    // 鍒濆鍖栧弬鏁板拰 PID
    g_ctx.grid_m = grid_size_m;
    g_ctx.default_grid_m = grid_size_m;
    g_ctx.pulses_per_meter = pulses_per_meter;
    g_ctx.pos_tol_m = path_corner_commit_lateral_gate_min_m;   // 浣嶇疆瀹瑰樊锛屽彲鎸夐渶瑕佽皟鏁?
    g_ctx.yaw_tol_deg = PATH_FOLLOW_YAW_TOLERANCE_DEG;  // 鑸悜瀹瑰樊
    g_ctx.max_v_mps = PATH_FOLLOW_MAX_LINEAR_SPEED_MPS;    // 鏈€澶х嚎閫熷害
    g_ctx.max_w_rad = PATH_FOLLOW_MAX_ANGULAR_SPEED_LIMIT;    // 瑙掗€熷害涓婇檺
    g_ctx.target_yaw_deg = 0.0f;
    g_ctx.heading_mode = PATH_FOLLOW_HEADING_FIXED;
    g_ctx.pose.x_m = 0.0f;
    g_ctx.pose.y_m = 0.0f;
    g_ctx.pose.yaw_deg = 0.0f;
    g_ctx.speed_cfg.segment_end_speed_cmps = SCURVE_SEGMENT_END_SPEED_CMPS;
    g_ctx.speed_cfg.hold_release_distance_m = path_hold_trim_release_distance;
    g_ctx.path = NULL;
    g_ctx.steps = 0;
    g_ctx.idx = 0;
    g_ctx.rotate_only_active = 0U;
    g_ctx.active = 0;
    g_ctx.pause_events_enabled = 0U;
    path_follow_apply_runtime_tuning();
    path_follow_reset_scurve_band_defaults();
    path_follow_reset_motion_profile_state();
    path_follow_clear_debug_state();
    path_follow_clear_pause_config();

    pid_world_init.fKp = PATH_FOLLOW_PID_WORLD_KP;  // 浣嶇疆璇樊鍒伴€熷害杈撳嚭
    pid_world_init.fKi = PATH_FOLLOW_PID_WORLD_KI;
    pid_world_init.fKd = PATH_FOLLOW_PID_WORLD_KD;
    pid_world_init.fMax_Iout = g_ctx.max_v_mps*100.0f;
    pid_world_init.fMax_Out = g_ctx.max_v_mps*100.0f;
    pid_world_init.alpha = PATH_FOLLOW_PID_WORLD_ALPHA;

    pid_stay_init.fKp = PATH_FOLLOW_PID_STAY_KP;  // 浣嶇疆璇樊鍒伴€熷害杈撳嚭
    pid_stay_init.fKi = PATH_FOLLOW_PID_STAY_KI;
    pid_stay_init.fKd = PATH_FOLLOW_PID_STAY_KD;
    pid_stay_init.fMax_Iout = PATH_FOLLOW_PID_STAY_MAX_IOUT_CMPS;
    pid_stay_init.fMax_Out = PATH_FOLLOW_PID_STAY_MAX_OUT_CMPS;
    pid_stay_init.alpha = PATH_FOLLOW_PID_STAY_ALPHA;

    pid_yaw_init.fKp = PATH_FOLLOW_PID_YAW_KP;  // 鑸悜璇樊鍒拌閫熷害杈撳嚭
    pid_yaw_init.fKi = PATH_FOLLOW_PID_YAW_KI;
    pid_yaw_init.fKd = PATH_FOLLOW_PID_YAW_KD;
    pid_yaw_init.fMax_Iout = g_ctx.max_w_rad;
    pid_yaw_init.fMax_Out = g_ctx.max_w_rad;
    pid_yaw_init.alpha = PATH_FOLLOW_PID_YAW_ALPHA;

    pid_accel_yaw_init.fKp = PATH_FOLLOW_PID_ACCEL_YAW_KP;  // 鑸悜璇樊鍒拌閫熷害杈撳嚭
    pid_accel_yaw_init.fKi = PATH_FOLLOW_PID_ACCEL_YAW_KI;
    pid_accel_yaw_init.fKd = PATH_FOLLOW_PID_ACCEL_YAW_KD;
    pid_accel_yaw_init.fMax_Iout = g_ctx.max_w_rad;
    pid_accel_yaw_init.fMax_Out = g_ctx.max_w_rad;
    pid_accel_yaw_init.alpha = PATH_FOLLOW_PID_ACCEL_YAW_ALPHA;

    PID_Init(&pid_world_x, &pid_world_init);
    PID_Init(&pid_stay, &pid_stay_init);
    PID_Init(&pid_stay_y, &pid_stay_init);
    PID_Init(&pid_world_y, &pid_world_init);
    PID_Init(&pid_yaw, &pid_yaw_init);
    PID_Init(&pid_accel_yaw, &pid_accel_yaw_init);
}

/**
 * @brief 閲嶇疆褰撳墠閲岀▼璁′綅濮裤€?
 *
 * 閲嶇疆浣嶅Э鏃朵細鍚屾椂娓呯┖骞崇Щ鎺у埗鐘舵€侊紝閬垮厤鏃ц矾寰勬畫鐣欑殑 PID 鍘嗗彶閲忕户缁綔鐢ㄣ€?
 *
 * @param x_m 鏂扮殑 X 鍧愭爣锛屽崟浣?m銆?
 * @param y_m 鏂扮殑 Y 鍧愭爣锛屽崟浣?m銆?
 * @param yaw_deg 鏂扮殑鑸悜瑙掞紝鍗曚綅 deg銆?
 */
void path_follow_reset_pose(float x_m, float y_m, float yaw_deg)
{
    g_ctx.pose.x_m = x_m;
    g_ctx.pose.y_m = y_m;
    g_ctx.pose.yaw_deg = path_follow_wrap_deg(yaw_deg);
    path_follow_reset_control_state();
}

/**
 * @brief 璁剧疆澶栭儴浣嶅Э杈撳叆鎺ュ彛銆?
 *
 * @param x_m 澶栭儴浣嶇疆 X锛屽崟浣?m銆?
 * @param y_m 澶栭儴浣嶇疆 Y锛屽崟浣?m銆?
 * @param valid 澶栭儴浣嶇疆鏄惁鏈夋晥銆?
 *
 * @note 褰撳墠鐗堟湰淇濈暀鎺ュ彛浣嗘湭鍦ㄦ湰妯″潡鍐呴儴鐩存帴浣跨敤銆?
 */
void path_follow_set_external_position(float x_m, float y_m, uint8 valid)
{
    (void)x_m;
    (void)y_m;
    (void)valid;
}

/**
 * @brief 璁剧疆涓€鏉℃柊鐨勮窡闅忚矾寰勩€?
 *
 * @param path 璺緞鐐规暟缁勬寚閽堛€?
 * @param steps 璺緞鐐规暟閲忋€?
 */
void path_follow_set_path(const Position *path, size_t steps)
{
    path_follow_set_path_pause_enabled(path, steps, 1U);
}

/**
 * @brief 璁剧疆涓€鏉℃柊鐨勮窡闅忚矾寰勶紝骞舵樉寮忔寚瀹氳璺緞鏄惁鍏佽瑙﹀彂 pause 浜嬩欢銆?
 *
 * @param path 璺緞鐐规暟缁勬寚閽堛€?
 * @param steps 璺緞鐐规暟閲忋€?
 * @param pause_events_enabled `1` 琛ㄧず鍏佽浣跨敤宸查厤缃殑 pause 绱㈠紩锛宍0` 琛ㄧず鏈矾寰勭鐢?pause銆?
 */
void path_follow_set_path_pause_enabled(const Position *path, size_t steps, uint8 pause_events_enabled)
{
    path_follow_apply_path(path, steps, g_ctx.default_grid_m, 0U, 1U, pause_events_enabled);
}

/**
 * @brief 閰嶇疆鏅€氬湴鍥?corner_path 涓婄殑鏆傚仠浜嬩欢鍒楄〃銆?
 *
 * @param pause_indices 闇€瑕佹殏鍋滅殑 target corner 绱㈠紩鏁扮粍锛屽彲涓?NULL銆?
 * @param pause_count pause_indices 涓殑鍏冪礌涓暟銆?
 * @param pause_ms 姣忎釜鏆傚仠鐐圭粺涓€鍋滅暀鏃堕暱锛屽崟浣?ms锛涗紶 0 鍙竻绌洪厤缃€?
 */
void path_follow_set_pause_indices(const size_t *pause_indices, size_t pause_count, uint32 pause_ms)
{
    size_t copy_count = 0U;
    size_t i;

    path_follow_clear_pause_config();
    if (pause_indices == NULL || pause_count == 0U || pause_ms == 0U)
    {
        return;
    }

    if (pause_count > PATH_FOLLOW_MAX_PAUSE_POINTS)
    {
        pause_count = PATH_FOLLOW_MAX_PAUSE_POINTS;
    }

    for (i = 0U; i < pause_count; ++i)
    {
        g_ctx.pause_indices[copy_count++] = pause_indices[i];
    }
    g_ctx.pause_count = copy_count;
    g_ctx.pause_cycles_cfg = (pause_ms * (uint32)PID_RATE + 999U) / 1000U;
    if (g_ctx.pause_cycles_cfg == 0U)
    {
        g_ctx.pause_cycles_cfg = 1U;
    }
}

/**
 * @brief 璁剧疆鍗曚釜绂绘暎鐩爣鐐瑰苟鐢熸垚涓存椂涓ょ偣璺緞銆?
 *
 * @param target_row 鐩爣鐐规墍鍦ㄧ綉鏍艰鍙枫€?
 * @param target_col 鐩爣鐐规墍鍦ㄧ綉鏍煎垪鍙枫€?
 */
void path_follow_set_target(int target_row, int target_col)
{
    g_single_target_path[0].row = (int)lroundf(g_ctx.pose.x_m / g_ctx.default_grid_m);
    g_single_target_path[0].col = (int)lroundf(g_ctx.pose.y_m / g_ctx.default_grid_m);
    g_single_target_path[1].row = target_row;
    g_single_target_path[1].col = target_col;
    path_follow_apply_path(g_single_target_path, 2U, g_ctx.default_grid_m, 0U, 1U, 0U);
}

void path_follow_set_target_yaw(float target_yaw_deg)
{
    g_ctx.target_yaw_deg = path_follow_wrap_deg(target_yaw_deg);
}

void path_follow_hold_current_yaw(void)
{
    path_follow_set_target_yaw(g_ctx.pose.yaw_deg);
}

void path_follow_start_rotate_to_yaw(float target_yaw_deg)
{
    path_follow_reset_control_state();
    PID_Clear(&pid_yaw);
    g_ctx.path = NULL;
    g_ctx.steps = 0U;
    g_ctx.idx = 0U;
    g_ctx.active = 0U;
    g_ctx.paused = 0U;
    g_ctx.pause_cycles_remaining = 0U;
    g_ctx.rotate_only_active = 1U;
    g_ctx.pause_events_enabled = 0U;
    path_follow_set_target_yaw(target_yaw_deg);
}

/**
 * @brief 鍚姩鍙戣溅鍓嶅浐瀹氬亸绉诲姩浣溿€?
 *
 * @param delta_x_m X 鏂瑰悜鍋忕Щ閲忥紝鍗曚綅 m銆?
 * @param delta_y_m Y 鏂瑰悜鍋忕Щ閲忥紝鍗曚綅 m銆?
 */
void path_follow_start_offset_move(float delta_x_m, float delta_y_m)
{
    float start_x_m = g_ctx.pose.x_m;
    float start_y_m = g_ctx.pose.y_m;
    path_follow_start_axis_move(start_x_m + delta_x_m,
                                start_y_m + delta_y_m,
                                g_prestart_offset_path,
                                sizeof(g_prestart_offset_path) / sizeof(g_prestart_offset_path[0]),
                                PRESTART_OFFSET_RESOLUTION_M);
}

/**
 * @brief 鍚姩浣嶅Э淇鍔ㄤ綔銆?
 *
 * 璇ュ嚱鏁颁細鐢熸垚涓€鏉＄煭涓存椂璺緞锛屼娇搴曠洏鎸夊綋鍓嶄綅缃紦鎱㈤潬杩戝閮ㄤ慨姝ｇ洰鏍囥€?
 *
 * @param target_x_m 淇鐩爣 X 鍧愭爣锛屽崟浣?m銆?
 * @param target_y_m 淇鐩爣 Y 鍧愭爣锛屽崟浣?m銆?
 */
void path_follow_start_pose_correction(float target_x_m, float target_y_m)
{
    path_follow_start_axis_move(target_x_m,
                                target_y_m,
                                g_pose_correction_path,
                                sizeof(g_pose_correction_path) / sizeof(g_pose_correction_path[0]),
                                PRESTART_OFFSET_RESOLUTION_M);
}
/**
 * @brief 鏍规嵁鍥涜疆缂栫爜鍣ㄥ拰褰撳墠鑸悜浼扮畻涓栫晫绯讳綅濮裤€?
 *
 * @param yaw_deg 褰撳墠 IMU 鑸悜瑙掞紝鍗曚綅 deg銆?
 */
static void update_odometry(float yaw_deg)
{
    if (g_ctx.pulses_per_meter <= 0.0f)
    {
        return;
    }

    float count_to_mps = ((float)PID_RATE) / g_ctx.pulses_per_meter;
    float w_ul = (float)up_L_all * count_to_mps;
    float w_ur = (float)up_R_all * count_to_mps;
    float w_dl = (float)down_L_all * count_to_mps;
    float w_dr = (float)down_R_all * count_to_mps;

    float vx_body = 0.25f * (w_ul + w_ur + w_dl + w_dr);
    float vy_body = 0.25f * (-w_ul + w_ur + w_dl - w_dr);
    float omega_body = (-w_ul + w_ur - w_dl + w_dr) / (2*D_X + 2*D_Y);
    // if (rx_plus_ry_cali != 0.0f)
    // {
    //     omega_body /= rx_plus_ry_cali;
    // }

    float dt = 1.0f / (float)PID_RATE;
    float yaw_rad = yaw_deg * ((float)M_PI / 180.0f);

    float cos_yaw = cosf(yaw_rad);
    float sin_yaw = sinf(yaw_rad);

    float vx_world = vx_body * cos_yaw - vy_body * sin_yaw;
    float vy_world = vx_body * sin_yaw + vy_body * cos_yaw;

    g_ctx.pose.x_m += vx_world * dt;
    g_ctx.pose.y_m += vy_world * dt;
    g_ctx.pose.yaw_deg = path_follow_wrap_deg(yaw_deg);
}

/**
 * @brief 鏍规嵁鐩爣鐐硅宸垽鏂綋鍓嶈矾寰勬涓昏酱鏂瑰悜銆?
 *
 * @param delta_x_m 鐩爣鐐圭浉瀵瑰綋鍓嶄綅缃殑 X 鏂瑰悜璇樊锛屽崟浣?m銆?
 * @param delta_y_m 鐩爣鐐圭浉瀵瑰綋鍓嶄綅缃殑 Y 鏂瑰悜璇樊锛屽崟浣?m銆?
 * @return `0` 闈欐锛宍1` X 娈碉紝`2` Y 娈碉紝`3` 鏂滄銆?
 */
static uint8 path_follow_resolve_segment_axis(float delta_x_m, float delta_y_m)
{
    float delta_x_abs = fabsf(delta_x_m);
    float delta_y_abs = fabsf(delta_y_m);
    const float axis_eps_m = 0.001f;

    if (delta_x_abs <= axis_eps_m && delta_y_abs <= axis_eps_m)
    {
        return 0U;
    }
    if (delta_y_abs <= axis_eps_m)
    {
        return 1U;
    }
    if (delta_x_abs <= axis_eps_m)
    {
        return 2U;
    }
    return 3U;
}

/**
 * @brief 灏嗚矾寰勮窡闅忕姸鎬佸垏鎹负瀹屾垚銆?
 *
 * @param out 杈撳嚭缁撴瀯浣撴寚閽堬紝鐢ㄤ簬鍥炲啓 `reached` 鏍囧織銆?
 * @return 鍥哄畾杩斿洖 `0`锛屼究浜庡湪璋冪敤鐐圭洿鎺ヤ綔涓哄け璐?缁撴潫鍒嗘敮浣跨敤銆?
 */
static uint8 path_follow_finish_path(path_follow_output_t *out)
{
    g_ctx.active = 0U;
    car_direction = 0U;
    path_follow_reset_control_state();
    if (out != NULL)
    {
        out->reached = 1U;
    }
    return 0U;
}

/**
 * @brief 涓哄綋鍓嶅懆鏈熷噯澶囪矾寰勫嚑浣曚俊鎭€?
 *
 * 璇ュ嚱鏁颁細璺宠繃宸茬粡鍒拌揪鐨勭洰鏍囩偣锛屽繀瑕佹椂鑷姩鎺ㄨ繘鍒颁笅涓€涓嫄鐐癸紱
 * 鑻ユ暣鏉¤矾寰勬墽琛屽畬姣曪紝鍒欏湪鍐呴儴瀹屾垚缁撴潫鏀跺熬銆?
 *
 * @param geometry 鍑犱綍淇℃伅杈撳嚭鎸囬拡銆?
 * @param out 鏈懆鏈熸帶鍒惰緭鍑烘寚閽堬紝鐢ㄤ簬璺緞缁撴潫鏃跺洖鍐欑姸鎬併€?
 * @return `1` 琛ㄧず鎴愬姛寰楀埌鏈夋晥鍑犱綍淇℃伅锛宍0` 琛ㄧず褰撳墠鏃犳湁鏁堟帶鍒剁洰鏍囥€?
 */
static uint8 path_follow_prepare_geometry(path_follow_geometry_t *geometry, path_follow_output_t *out)
{
    if (geometry == NULL)
    {
        return 0U;
    }

    while (g_ctx.active && g_ctx.path && g_ctx.idx < g_ctx.steps)
    {
        uint8 pause_target;

        Position target;

        path_follow_sync_pause_cursor(g_ctx.idx);
        target = g_ctx.path[g_ctx.idx];

        geometry->target_point = target;
        path_follow_get_compensated_target_position(g_ctx.idx,
                                                    target,
                                                    &geometry->target_x_m,
                                                    &geometry->target_y_m);
        geometry->delta_x_m = geometry->target_x_m - g_ctx.pose.x_m;
        geometry->delta_y_m = geometry->target_y_m - g_ctx.pose.y_m;
        geometry->distance_m = sqrtf(geometry->delta_x_m * geometry->delta_x_m +
                                     geometry->delta_y_m * geometry->delta_y_m);
        pause_target = path_follow_target_requires_pause(g_ctx.idx);

        if (geometry->distance_m >= g_ctx.pos_tol_m)
        {
            geometry->dir_x = geometry->delta_x_m / geometry->distance_m;
            geometry->dir_y = geometry->delta_y_m / geometry->distance_m;
            geometry->segment_axis = path_follow_resolve_segment_axis(geometry->delta_x_m,
                                                                      geometry->delta_y_m);
            car_direction = geometry->segment_axis;
            return 1U;
        }

        if ((g_ctx.idx + 1U) < g_ctx.steps)
        {
            path_follow_commit_raw_target_pose(target);
            if (pause_target)
            {
                path_follow_enter_pause(g_ctx.idx);
                return 0U;
            }
#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER
            if (path_follow_enable_corner_handover)
            {
                path_follow_reset_corner_handover_state();
                path_follow_invalidate_active_profile();
            }
#endif
            g_ctx.idx++;
            continue;
        }

        if (pause_target)
        {
            path_follow_commit_raw_target_pose(target);
            path_follow_enter_pause(g_ctx.idx);
            return 0U;
        }
        path_follow_commit_raw_target_pose(target);
        return path_follow_finish_path(out);
    }

    car_direction = 0U;
    return 0U;
}

/**
 * @brief 涓哄綋鍓嶈矾寰勬鏋勯€犱竴娆℃€х殑鏍囧噯 S 鏇茬嚎 profile銆?
 *
 * @note 璇ュ嚱鏁板彧鍦ㄨ繘鍏ユ柊璺緞娈点€佸垏鎹㈢洰鏍囩偣鎴?profile 琚樉寮忓け鏁堟椂璋冪敤锛?
 *       姝ｅ父鎵ц鏈熶笉浼氶噸澶嶉噸寤?profile銆?
 *
 * @param geometry 褰撳墠鍛ㄦ湡璺緞鍑犱綍淇℃伅銆?
 * @param speed_plan 閫熷害瑙勫垝缁撴灉杈撳嚭锛岀敤浜庡洖濉鏈€熷害涓庡畨鍏ㄩ€熷害涓婇檺銆?
 * @return `1` 琛ㄧず褰撳墠娈?profile 鏋勯€犳垚鍔燂紝`0` 琛ㄧず鏋勯€犲け璐ャ€?
 */
static uint8 path_follow_build_active_profile(const path_follow_geometry_t *geometry,
                                              path_follow_speed_plan_t *speed_plan)
{
    path_follow_scurve_profile_t profile = {0};
    path_follow_scurve_runtime_cfg_t selected_cfg = {0};
    float start_speed_cmps;

    if (geometry == NULL || speed_plan == NULL)
    {
        return 0U;
    }

    path_follow_select_scurve_band(geometry->distance_m, &selected_cfg);
    g_ctx.active_scurve_cfg = selected_cfg;

    speed_plan->end_speed_cmps = fminf(path_follow_compute_segment_end_speed(),
                                       g_ctx.active_scurve_cfg.max_speed_cmps);
    speed_plan->safety_cap_cmps = path_follow_compute_brake_speed_cap(geometry->distance_m,
                                                                      speed_plan->end_speed_cmps,
                                                                      g_ctx.active_scurve_cfg.max_speed_cmps,
                                                                      g_ctx.active_scurve_cfg.accel_cmpss);

    start_speed_cmps = fmaxf(g_ctx.last_ref_speed_cmps, 0.0f);
    start_speed_cmps = fminf(start_speed_cmps, speed_plan->safety_cap_cmps);

    if (!path_follow_build_scurve_profile(&profile,
                                          geometry->distance_m * 100.0f,
                                          start_speed_cmps,
                                          speed_plan->end_speed_cmps,
                                          g_ctx.active_scurve_cfg.max_speed_cmps,
                                          g_ctx.active_scurve_cfg.accel_cmpss,
                                          g_ctx.active_scurve_cfg.jerk_cmpsss))
    {
        path_follow_invalidate_active_profile();
        return 0U;
    }

    g_ctx.active_profile = profile;
    g_ctx.profile_time_s = 0.0f;
    g_ctx.profile_target_idx = g_ctx.idx;
    g_ctx.profile_active = 1U;
    speed_plan->end_speed_cmps = profile.v1;
    return 1U;
}

/**
 * @brief 瑙勫垝褰撳墠鍛ㄦ湡鐨勬爣閲忛€熷害鍙傝€冦€?
 *
 * 褰撳墠瀹炵幇閲囩敤鈥滄暣娈典竴娆¤鍒?+ 鎸夌疮璁℃椂闂磋繛缁噰鏍封€濈殑鏍囧噯 S 鏇茬嚎鎵ц鏂瑰紡锛?
 * 1. 浠呭湪杩涘叆鏂拌矾寰勬鏃舵瀯閫犱竴娆″畬鏁?profile锛?
 * 2. profile 鍐呭浐瀹氳娈电殑璧风偣閫熷害銆佺粓鐐归€熷害涓庣害鏉燂紱
 * 3. 姣忎釜鎺у埗鍛ㄦ湡鍙帹杩涜娈电殑绱鏃堕棿骞堕噰鏍烽€熷害锛?
 * 4. 褰撳墠鍓╀綑璺濈鍙綔涓哄畨鍏ㄧ洃鎶ゅ眰锛屼笉鍐嶅弬涓庝富杞ㄨ抗婊氬姩閲嶅缓锛?
 * 5. 鍙湁 profile 鏋勯€犲け璐ユ椂锛屾墠閫€鍖栧埌寮傚父淇濇姢閫熷害銆?
 *
 * @param geometry 褰撳墠鍛ㄦ湡璺緞鍑犱綍淇℃伅銆?
 * @param speed_plan 閫熷害瑙勫垝缁撴灉杈撳嚭銆?
 */

static void path_follow_plan_speed(const path_follow_geometry_t *geometry,
                                   path_follow_speed_plan_t *speed_plan)
{
    const float sample_dt_s = 1.0f / (float)PID_RATE;
    uint8 build_ok = 1U;

    if (geometry == NULL || speed_plan == NULL)
    {
        return;
    }

    speed_plan->end_speed_cmps = path_follow_compute_segment_end_speed();
    speed_plan->safety_cap_cmps = 0.0f;
    speed_plan->ref_speed_cmps = 0.0f;

    if (!g_ctx.profile_active || g_ctx.profile_target_idx != g_ctx.idx)
    {
        build_ok = path_follow_build_active_profile(geometry, speed_plan);
    }
    else
    {
        speed_plan->end_speed_cmps = g_ctx.active_profile.v1;
        speed_plan->safety_cap_cmps = path_follow_compute_brake_speed_cap(geometry->distance_m,
                                                                          speed_plan->end_speed_cmps,
                                                                          g_ctx.active_scurve_cfg.max_speed_cmps,
                                                                          g_ctx.active_scurve_cfg.accel_cmpss);
    }

    if (g_ctx.profile_active)
    {
        g_ctx.profile_time_s += sample_dt_s;
        if (g_ctx.profile_time_s > g_ctx.active_profile.T)
        {
            g_ctx.profile_time_s = g_ctx.active_profile.T;
        }

        speed_plan->ref_speed_cmps = path_follow_sample_scurve_velocity(g_ctx.profile_time_s,
                                                                        &g_ctx.active_profile);
        speed_plan->end_speed_cmps = g_ctx.active_profile.v1;
        speed_plan->safety_cap_cmps = path_follow_compute_brake_speed_cap(geometry->distance_m,
                                                                          speed_plan->end_speed_cmps,
                                                                          g_ctx.active_scurve_cfg.max_speed_cmps,
                                                                          g_ctx.active_scurve_cfg.accel_cmpss);
    }
    else if (!build_ok)
    {
        speed_plan->ref_speed_cmps = path_follow_compute_profile_fault_speed(g_ctx.last_ref_speed_cmps,
                                                                             speed_plan->safety_cap_cmps,
                                                                             g_ctx.active_scurve_cfg.accel_cmpss);
    }

    speed_plan->ref_speed_cmps = clamp_sym(speed_plan->ref_speed_cmps,
                                           g_ctx.active_scurve_cfg.max_speed_cmps);
    speed_plan->ref_speed_cmps = fminf(speed_plan->ref_speed_cmps,
                                       speed_plan->safety_cap_cmps);
    speed_plan->ref_speed_cmps = fmaxf(speed_plan->ref_speed_cmps, 0.0f);

    if (geometry->distance_m <= g_ctx.pos_tol_m)
    {
        speed_plan->ref_speed_cmps = 0.0f;
    }

    g_ctx.last_ref_speed_cmps = speed_plan->ref_speed_cmps;
}

/**
 * @brief 璁＄畻瀹氱偣淇濇寔淇鐨勬贩鍚堟潈閲嶃€?
 *
 * @param distance_m 褰撳墠璺濈洰鏍囩偣鐨勫墿浣欒窛绂伙紝鍗曚綅 m銆?
 * @return `[0, 1]` 鑼冨洿鍐呯殑淇濇寔鏉冮噸銆?
 */
static float path_follow_compute_hold_blend(float distance_m)
{
    float release_distance_m = g_ctx.speed_cfg.hold_release_distance_m;

    if (distance_m >= release_distance_m)
    {
        return 0.0f;
    }
    if (distance_m <= g_ctx.pos_tol_m)
    {
        return 1.0f;
    }
    if (release_distance_m <= g_ctx.pos_tol_m)
    {
        return 1.0f;
    }

    return 1.0f - ((distance_m - g_ctx.pos_tol_m) /
                   (release_distance_m - g_ctx.pos_tol_m));
}

/**
 * @brief 鍒ゆ柇褰撳墠鐩爣鐐规槸鍚﹀睘浜庢櫘閫氳矾绾夸腑鐨勪腑闂存嫄鐐广€?
 *
 * @note 杩欓噷鏄惧紡鎺掗櫎鍚姩鍋忕Щ/浣嶅Э淇浣跨敤鐨勪复鏃剁粏缃戞牸璺緞锛屽彧鍦ㄦ甯稿湴鍥捐矾寰勪笂鐢熸晥銆?
 *
 * @return `1` 琛ㄧず褰撳墠鐩爣鏄櫘閫氳矾绾夸腑浠嶆湁鍚庣画娈电殑鎷愮偣锛宍0` 琛ㄧず涓嶆槸銆?
 */
static uint8 path_follow_is_route_corner_target(void)
{
    const float grid_eps_m = 1e-6f;
    Position prev_point;
    Position curr_point;
    Position next_point;
    int d1_row;
    int d1_col;
    int d2_row;
    int d2_col;

    if (g_ctx.path == NULL || g_ctx.steps < 3U)
    {
        return 0U;
    }
    if (g_ctx.idx == 0U || (g_ctx.idx + 1U) >= g_ctx.steps)
    {
        return 0U;
    }
    if (fabsf(g_ctx.grid_m - g_ctx.default_grid_m) > grid_eps_m)
    {
        return 0U;
    }

    prev_point = g_ctx.path[g_ctx.idx - 1U];
    curr_point = g_ctx.path[g_ctx.idx];
    next_point = g_ctx.path[g_ctx.idx + 1U];

    d1_row = curr_point.row - prev_point.row;
    d1_col = curr_point.col - prev_point.col;
    d2_row = next_point.row - curr_point.row;
    d2_col = next_point.col - curr_point.col;

    return (d1_row != d2_row || d1_col != d2_col) ? 1U : 0U;
}


/**
 * @brief [CornerHandover绉绘] 灏?0~1 绾挎€ц繘搴︽暣褰㈡垚浜旀 smoothstep 杩涘害銆?
 *
 * @param t 绾挎€ц繘搴︼紝鑼冨洿鏈熸湜涓?[0, 1]銆?
 * @return S 褰㈡暣褰㈠悗鐨勮繘搴︼紝鑼冨洿涓?[0, 1]銆?
 */
#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER
static float path_follow_s_curve_01(float t)
{
    if (t <= 0.0f)
    {
        return 0.0f;
    }
    if (t >= 1.0f)
    {
        return 1.0f;
    }

    return t * t * t * (t * (t * 6.0f - 15.0f) + 10.0f);
}
  
static uint8 path_follow_check_corner_handover_timeout(void)
{
    static uint8 last_active = 0U;
    static uint32 handover_tick = 0U;
    static uint32 handover_idx = 0U;
    const uint32 timeout_tick = PATH_CORNER_HANDOVER_TIMEOUT_S * (uint32)PID_RATE;

    if (!g_ctx.corner_handover_active)
    {
        last_active = 0U;
        handover_tick = 0U;
        handover_idx = 0U;
        return 0U;
    }

    if (!last_active || handover_idx != (uint32)g_ctx.idx)
    {
        last_active = 1U;
        handover_tick = 0U;
        handover_idx = (uint32)g_ctx.idx;
        return 0U;
    }

    if (handover_tick < 0xFFFFFFFFU)
    {
        handover_tick++;
    }

    if (handover_tick >= timeout_tick)
    {
        path_follow_reset_corner_handover_state();
        last_active = 0U;
        handover_tick = 0U;
        handover_idx = 0U;
        return 1U;
    }

    return 0U;
}

/**
 * @brief [CornerHandover閲嶆瀯] 鍦ㄦ櫘閫氫腑闂存嫄鐐瑰墠骞虫粦浜ゆ帴涓栫晫绯婚€熷害鏂瑰悜銆?
 *
 * @note 杩欓噷涓嶆敼鍙樺師鏈夋绾?S 鏇茬嚎鐨勬爣閲忛€熷害瑙勫垝锛屽彧鍦ㄦ櫘閫氫腑闂存嫄鐐逛笂
 *       鎸変笂涓€娈垫姇褰辫繘搴﹁繘鍏?handover锛屽苟鍦ㄥ垏娈靛墠淇濇寔璇ヨ繍琛屾€侀攣瀛樸€?
 *
 * @param geometry 褰撳墠鍛ㄦ湡璺緞鍑犱綍淇℃伅銆?
 * @param ref_speed_cmps 褰撳墠鍛ㄦ湡鏍囬噺閫熷害鍙傝€冿紝鍗曚綅 cm/s銆?
 * @param vx_world_cmps 涓栫晫绯?X 鏂瑰悜閫熷害杈撳嚭銆?
 * @param vy_world_cmps 涓栫晫绯?Y 鏂瑰悜閫熷害杈撳嚭銆?
 * @return `1` 琛ㄧず鏈懆鏈熷凡搴旂敤鎷愮偣浜ゆ帴锛宍0` 琛ㄧず鏈簲鐢ㄣ€?
 */
static uint8 path_follow_try_corner_handover(const path_follow_geometry_t *geometry,
                                             float ref_speed_cmps,
                                             float *vx_world_cmps,
                                             float *vy_world_cmps)
{
    const float eps = 1e-6f;
    const Position *prev_point = NULL;
    const Position *curr_point = NULL;
    const Position *next_point = NULL;
    float segment_progress_m = 0.0f;
    float segment_length_m = 0.0f;
    float lateral_error_m = 0.0f;
    float remaining_along_m;
    float prev_dx_m;
    float prev_dy_m;
    float next_dx_m;
    float next_dy_m;
    float prev_length_m;
    float next_length_m;
    float enter_distance_m;
    float commit_distance_m;
    float t;
    float k;
    float v_scale;
    float turn_cos;
    float turn_severity;
    float k_drop;
    float old_x;
    float old_y;
    float new_x;
    float new_y;
    float mix_x;
    float mix_y;
    float mix_norm;

    if (geometry == NULL || vx_world_cmps == NULL || vy_world_cmps == NULL)
    {
        return 0U;
    }
    if (!path_follow_enable_corner_handover)
    {
        return 0U;
    }
    if (!path_follow_is_route_corner_target())
    {
        return 0U;
    }
    if (path_follow_target_requires_pause(g_ctx.idx))
    {
        return 0U;
    }
    if (!path_follow_get_segment_points(&prev_point, &curr_point, &next_point) ||
        prev_point == NULL || curr_point == NULL || next_point == NULL)
    {
        return 0U;
    }
    if (!path_follow_compute_segment_progress_m(&g_ctx.pose,
                                                prev_point,
                                                curr_point,
                                                &segment_progress_m,
                                                &segment_length_m,
                                                &lateral_error_m))
    {
        return 0U;
    }


    prev_dx_m = (curr_point->row - prev_point->row) * g_ctx.grid_m;
    prev_dy_m = (curr_point->col - prev_point->col) * g_ctx.grid_m;
    next_dx_m = (next_point->row - curr_point->row) * g_ctx.grid_m;
    next_dy_m = (next_point->col - curr_point->col) * g_ctx.grid_m;
    prev_length_m = sqrtf(prev_dx_m * prev_dx_m + prev_dy_m * prev_dy_m);
    next_length_m = sqrtf(next_dx_m * next_dx_m + next_dy_m * next_dy_m);
    if (prev_length_m <= eps || next_length_m <= eps)
    {
        return 0U;
    }

/*     enter_distance_m = path_follow_compute_corner_enter_distance_m(prev_length_m, next_length_m);
    commit_distance_m = path_follow_compute_corner_commit_distance_m(prev_length_m, next_length_m); */
    enter_distance_m = path_corner_handover_enter_distance_m;
    commit_distance_m = path_corner_handover_commit_distance_m;
    if (enter_distance_m <= (commit_distance_m + PATH_CORNER_HANDOVER_WINDOW_GAP_MIN_M))
    {
        enter_distance_m = commit_distance_m + PATH_CORNER_HANDOVER_WINDOW_GAP_MIN_M;
    }

    if (g_ctx.corner_handover_active)
    {
        if (g_ctx.corner_handover_idx != g_ctx.idx)
        {
            path_follow_reset_corner_handover_state();
        }
        else
        {
            if (g_ctx.corner_enter_distance_m > 0.0f)
            {
                enter_distance_m = g_ctx.corner_enter_distance_m;
            }
            if (g_ctx.corner_commit_distance_m > 0.0f)
            {
                commit_distance_m = g_ctx.corner_commit_distance_m;
            }
        }
    }
    if (!g_ctx.corner_handover_active)
    {
        g_ctx.corner_handover_idx = g_ctx.idx;
        g_ctx.corner_enter_distance_m = enter_distance_m;
        g_ctx.corner_commit_distance_m = commit_distance_m;
    }
    if (enter_distance_m <= (commit_distance_m + PATH_CORNER_HANDOVER_WINDOW_GAP_MIN_M))
    {
        enter_distance_m = commit_distance_m + PATH_CORNER_HANDOVER_WINDOW_GAP_MIN_M;
    }

    remaining_along_m = segment_length_m - segment_progress_m;
    if (remaining_along_m < 0.0f)
    {
        remaining_along_m = 0.0f;
    }

    if (!g_ctx.corner_handover_active)
    {
        if (remaining_along_m >= enter_distance_m)
        {
            return 0U;
        }
        g_ctx.corner_handover_active = 1U;
    }
        if (path_follow_check_corner_handover_timeout())
    {
        return 0U;
    }


    old_x = geometry->dir_x;
    old_y = geometry->dir_y;

    new_x = next_dx_m / next_length_m;
    new_y = next_dy_m / next_length_m;
    turn_cos = old_x * new_x + old_y * new_y;
    turn_cos = fminf(fmaxf(turn_cos, -1.0f), 1.0f);
    /* 鐩磋鏃朵负 0锛?0 搴﹀強浠ヤ笂鎷愯鎸?1 澶勭悊銆?*/
    turn_severity = fminf(fmaxf(1.0f - turn_cos, 0.0f), 1.0f);

    t = (enter_distance_m - remaining_along_m) / (enter_distance_m - commit_distance_m);
    t = fminf(fmaxf(t, 0.0f), 1.0f);
    k = path_follow_s_curve_01(t);
    k_drop = PATH_CORNER_HANDOVER_K_DROP * turn_severity;
    v_scale = 1.0f - k_drop * 4.0f * k * (1.0f - k);
    v_scale = fmaxf(v_scale, 0.0f);

    mix_x = old_x * (1.0f - k) + new_x * k;
    mix_y = old_y * (1.0f - k) + new_y * k;
    mix_norm = sqrtf(mix_x * mix_x + mix_y * mix_y);
    if (mix_norm <= eps)
    {
        return 0U;
    }

    mix_x /= mix_norm;
    mix_y /= mix_norm;
    *vx_world_cmps = ref_speed_cmps * v_scale * mix_x;
    *vy_world_cmps = ref_speed_cmps * v_scale * mix_y;
    return 1U;
}
#endif

#if PATH_FOLLOW_ENABLE_LINE_GUIDE
static uint8 path_follow_apply_line_guidance(float ref_speed_cmps,
                                             float *vx_world_cmps,
                                             float *vy_world_cmps)
{
    const Position *prev_point = NULL;
    const Position *curr_point = NULL;
    float start_x_m;
    float start_y_m;
    float end_x_m;
    float end_y_m;
    float segment_progress_m = 0.0f;
    float segment_length_m = 0.0f;
    float lateral_error_m = 0.0f;
    float seg_dx_m;
    float seg_dy_m;
    float seg_norm_m;
    float tan_x;
    float tan_y;
    float normal_x;
    float normal_y;
    float effective_error_m;
    float abs_error_cm;
    float guide_sign;
    float trim_cmps;

    if (vx_world_cmps == NULL || vy_world_cmps == NULL)
    {
        return 0U;
    }
    if (!path_follow_get_segment_points(&prev_point, &curr_point, NULL) ||
        prev_point == NULL || curr_point == NULL)
    {
        return 0U;
    }
    if (g_ctx.idx == 0U)
    {
        return 0U;
    }

    path_follow_get_raw_target_position(*prev_point,
                                        &start_x_m,
                                        &start_y_m);
    path_follow_get_compensated_target_position(g_ctx.idx,
                                                *curr_point,
                                                &end_x_m,
                                                &end_y_m);
    if (!path_follow_compute_segment_progress_xy_m(&g_ctx.pose,
                                                   start_x_m,
                                                   start_y_m,
                                                   end_x_m,
                                                   end_y_m,
                                                   &segment_progress_m,
                                                   &segment_length_m,
                                                   &lateral_error_m))
    {
        return 0U;
    }

    seg_dx_m = end_x_m - start_x_m;
    seg_dy_m = end_y_m - start_y_m;
    seg_norm_m = sqrtf(seg_dx_m * seg_dx_m + seg_dy_m * seg_dy_m);
    if (seg_norm_m <= 1e-6f)
    {
        return 0U;
    }

    tan_x = seg_dx_m / seg_norm_m;
    tan_y = seg_dy_m / seg_norm_m;
    normal_x = -tan_y;
    normal_y = tan_x;

    if (fabsf(lateral_error_m) <= PATH_LINE_GUIDE_DEADBAND_M)
    {
        effective_error_m = 0.0f;
    }
    else if (lateral_error_m > 0.0f)
    {
        effective_error_m = lateral_error_m - PATH_LINE_GUIDE_DEADBAND_M;
    }
    else
    {
        effective_error_m = lateral_error_m + PATH_LINE_GUIDE_DEADBAND_M;
    }

    abs_error_cm = fabsf(effective_error_m * 100.0f);
    guide_sign = (effective_error_m > 0.0f) ? -1.0f : 1.0f;

    /*
     * 鐩寸嚎娈垫硶鍚戠籂鍋忛噰鐢ㄢ€滄渶灏忎慨姝ｉ€熷害鍓嶉 + Kp鈥濓細
     * - 璇樊涓€鏃﹁秺杩囨鍖猴紝鍏堢粰涓€涓渶灏忎晶鍚戜慨姝ｉ€熷害锛屽府鍔╁厠鏈嶉潤鎽╂摝锛?
     * - 鍐嶅彔鍔犱笌璇樊鎴愭姣旂殑淇閲忥紝淇濇寔瓒婂亸瓒婃媺鐨勮秼鍔裤€?
     */
    trim_cmps = path_line_guide_kp * abs_error_cm;
    if (trim_cmps > 0.0f)
    {
        trim_cmps += path_line_guide_min_cmps;
    }
    trim_cmps *= guide_sign;
    trim_cmps = clamp_sym(trim_cmps, PATH_LINE_GUIDE_MAX_CMPS);

    *vx_world_cmps = ref_speed_cmps * tan_x + trim_cmps * normal_x;
    *vy_world_cmps = ref_speed_cmps * tan_y + trim_cmps * normal_y;
    return 1U;
}
#endif

/**
 * @brief 鍦ㄦ帴杩戠洰鏍囩偣鏃跺彔鍔犱綅缃?PID 淇濇寔淇銆?
 *
 * @param geometry 褰撳墠鍛ㄦ湡璺緞鍑犱綍淇℃伅銆?
 * @param motion_cmd 杩愬姩鍛戒护缁撴瀯浣擄紝鍑芥暟浼氱洿鎺ュ湪涓栫晫绯诲钩绉婚€熷害涓婂彔鍔犱慨姝ｉ噺銆?
 */
static void path_follow_apply_hold_trim(const path_follow_geometry_t *geometry,
                                        path_follow_motion_cmd_t *motion_cmd)
{
    float hold_blend;

    if (geometry == NULL || motion_cmd == NULL)
    {
        return;
    }

    hold_blend = path_follow_compute_hold_blend(geometry->distance_m);
    if (hold_blend <= 0.0f)
    {
        return;
    }

#if !PATH_FOLLOW_ENABLE_CORNER_DUAL_AXIS_TRIM
    if (path_follow_is_route_corner_target())
    {
        return;
    }
#elif PATH_FOLLOW_COMPILE_CORNER_HANDOVER
    /*
     * handover 鍚敤鏃讹紝鎷愮偣闄勮繎浠嶄繚鐣欏弻杞村畾鐐逛慨姝ｏ紝浣嗛檷浣庢潈閲嶏紝
     * 閬垮厤瀵瑰垏鍚戦€熷害浜ゆ帴鏂藉姞杩囧己鎷夋壇銆?
     */
    if (path_follow_enable_corner_handover && path_follow_is_route_corner_target())
    {
        hold_blend *= path_follow_corner_hold_trim_scale;
    }
#endif

    motion_cmd->vx_world_cmps += hold_blend *
                                 PID_Location_Calculate(&pid_stay,
                                                        g_ctx.pose.x_m * 100.0f,
                                                        geometry->target_x_m * 100.0f);
    motion_cmd->vy_world_cmps += hold_blend *
                                 PID_Location_Calculate(&pid_stay_y,
                                                        g_ctx.pose.y_m * 100.0f,
                                                        geometry->target_y_m * 100.0f);
}

/**
 * @brief 灏嗕笘鐣岀郴骞崇Щ閫熷害鍚戦噺闄愬埗鍦ㄥ厑璁哥殑鏈€澶фā闀垮唴銆?
 *
 * @param motion_cmd 杩愬姩鍛戒护缁撴瀯浣撱€?
 */
static void path_follow_limit_world_speed(path_follow_motion_cmd_t *motion_cmd)
{
    float max_speed_cmps;
    float speed_norm;
    float scale;

    if (motion_cmd == NULL)
    {
        return;
    }

    max_speed_cmps = g_ctx.active_scurve_cfg.max_speed_cmps;
    if (max_speed_cmps <= 0.0f)
    {
        max_speed_cmps = path_follow_mps_to_cmps(g_path_follow_scurve_band_default_cfg[PATH_FOLLOW_SCURVE_BAND_COUNT - 1U].vmax_mps);
    }

    speed_norm = sqrtf(motion_cmd->vx_world_cmps * motion_cmd->vx_world_cmps +
                       motion_cmd->vy_world_cmps * motion_cmd->vy_world_cmps);
    if (speed_norm <= max_speed_cmps || speed_norm <= 0.0f)
    {
        return;
    }

    scale = max_speed_cmps / speed_norm;
    motion_cmd->vx_world_cmps *= scale;
    motion_cmd->vy_world_cmps *= scale;
}

/**
 * @brief 鏍规嵁鍑犱綍鏂瑰悜鍜屾爣閲忛€熷害鐢熸垚杩愬姩鍛戒护銆?
 *
 * 璇ュ嚱鏁板厛鍦ㄤ笘鐣屽潗鏍囩郴涓嬬敓鎴愬钩绉婚€熷害锛屽啀鍙犲姞杩戠洰鏍囦繚鎸佷慨姝ｏ紝
 * 鏈€鍚庤浆鎹㈠埌杞︿綋绯昏緭鍑虹粰搴曠洏杩愬姩瀛﹂€嗚В銆?
 *
 * @param geometry 褰撳墠鍛ㄦ湡璺緞鍑犱綍淇℃伅銆?
 * @param speed_plan 褰撳墠鍛ㄦ湡閫熷害瑙勫垝缁撴灉銆?
 * @param yaw_deg 褰撳墠鑸悜瑙掞紝鍗曚綅 deg銆?
 * @param motion_cmd 杩愬姩鍛戒护杈撳嚭銆?
 */
static void path_follow_build_motion_command(const path_follow_geometry_t *geometry,
                                             const path_follow_speed_plan_t *speed_plan,
                                             float yaw_deg,
                                             path_follow_motion_cmd_t *motion_cmd)
{
    float yaw_rad;
    float cos_yaw;
    float sin_yaw;
    float hold_blend;
#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER
    uint8 handover_active = 0U;
#endif

    if (geometry == NULL || speed_plan == NULL || motion_cmd == NULL)
    {
        return;
    }

    motion_cmd->vx_world_cmps = speed_plan->ref_speed_cmps * geometry->dir_x;
    motion_cmd->vy_world_cmps = speed_plan->ref_speed_cmps * geometry->dir_y;
    hold_blend = path_follow_compute_hold_blend(geometry->distance_m);

#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER
    /*
     * [CornerHandover绉绘]
     * 鍏堝熀浜庡綋鍓嶆爣閲忛€熷害寰楀埌鍩虹涓栫晫绯婚€熷害锛屽啀鍦ㄦ櫘閫氫腑闂存嫄鐐瑰墠灏濊瘯鍋氭柟鍚戜氦鎺ャ€?
     * 鍚庣画浠嶄繚鐣欏師鐗堢殑 hold trim銆佷笘鐣岀郴闄愬箙鍜岃溅浣撶郴鍙樻崲锛屼笉鏀瑰彉鐜版湁涓婚摼璺兘鍔涖€?
     */
    if (path_follow_enable_corner_handover)
    {
        handover_active = path_follow_try_corner_handover(geometry,
                                                          speed_plan->ref_speed_cmps,
                                                          &motion_cmd->vx_world_cmps,
                                                          &motion_cmd->vy_world_cmps);
    }
    else
    {
        path_follow_reset_corner_handover_state();
    }
#endif
#if PATH_FOLLOW_ENABLE_LINE_GUIDE
    if (
#if PATH_FOLLOW_COMPILE_CORNER_HANDOVER
        !handover_active &&
#endif
        hold_blend <= 0.0f)
    {
        (void)path_follow_apply_line_guidance(speed_plan->ref_speed_cmps,
                                              &motion_cmd->vx_world_cmps,
                                              &motion_cmd->vy_world_cmps);
    }
#endif

    if (hold_blend > 0.0f)
    {
        path_follow_apply_hold_trim(geometry, motion_cmd);
    }
    path_follow_limit_world_speed(motion_cmd);

    yaw_rad = yaw_deg * ((float)M_PI / 180.0f);
    cos_yaw = cosf(yaw_rad);
    sin_yaw = sinf(yaw_rad);

    motion_cmd->vx_body_cmps = motion_cmd->vx_world_cmps * cos_yaw +
                               motion_cmd->vy_world_cmps * sin_yaw;
    motion_cmd->vy_body_cmps = -motion_cmd->vx_world_cmps * sin_yaw +
                               motion_cmd->vy_world_cmps * cos_yaw;
}

/**
 * @brief 瑙勫垝褰撳墠鍛ㄦ湡鐨勫Э鎬佹帶鍒惰緭鍑恒€?
 *
 * @param yaw_deg 褰撳墠鑸悜瑙掞紝鍗曚綅 deg銆?
 * @param attitude_plan 濮挎€佽鍒掔粨鏋滆緭鍑恒€?
 */
static void path_follow_plan_attitude(float yaw_deg, path_follow_attitude_plan_t *attitude_plan)
{
    float omega_cmd_degps;
    float yaw_error_deg;

    if (attitude_plan == NULL)
    {
        return;
    }

    attitude_plan->target_yaw_deg = g_ctx.target_yaw_deg;
    if (g_ctx.heading_mode != PATH_FOLLOW_HEADING_FIXED)
    {
        attitude_plan->target_yaw_deg = 0.0f;
    }

    attitude_plan->target_yaw_deg = path_follow_wrap_deg(attitude_plan->target_yaw_deg);
    yaw_error_deg = path_follow_yaw_error_deg(yaw_deg, attitude_plan->target_yaw_deg);
    omega_cmd_degps = PID_Location_Calculate(&pid_yaw, 0.0f, yaw_error_deg);
    omega_cmd_degps = clamp_sym(omega_cmd_degps, g_ctx.max_w_rad);
    attitude_plan->omega_cmd_radps = omega_cmd_degps * ((float)M_PI / 180.0f);
}

/**
 * @brief 淇濆瓨褰撳墠鍛ㄦ湡鐨勮皟璇曠姸鎬佸揩鐓с€?
 *
 * @param geometry 褰撳墠鍛ㄦ湡璺緞鍑犱綍淇℃伅銆?
 * @param speed_plan 褰撳墠鍛ㄦ湡閫熷害瑙勫垝缁撴灉銆?
 * @param attitude_plan 褰撳墠鍛ㄦ湡濮挎€佽鍒掔粨鏋溿€?
 * @param motion_cmd 褰撳墠鍛ㄦ湡杩愬姩鍛戒护銆?
 */
static void path_follow_store_debug_state(const path_follow_geometry_t *geometry,
                                          const path_follow_speed_plan_t *speed_plan,
                                          const path_follow_attitude_plan_t *attitude_plan,
                                          const path_follow_motion_cmd_t *motion_cmd)
{
    if (geometry == NULL || speed_plan == NULL || attitude_plan == NULL || motion_cmd == NULL)
    {
        path_follow_clear_debug_state();
        return;
    }

    g_ctx.debug.distance_m = geometry->distance_m;
    g_ctx.debug.dir_x = geometry->dir_x;
    g_ctx.debug.dir_y = geometry->dir_y;
    g_ctx.debug.speed_ref_cmps = speed_plan->ref_speed_cmps;
    g_ctx.debug.target_yaw_deg = attitude_plan->target_yaw_deg;
    g_ctx.debug.vx_world_cmps = motion_cmd->vx_world_cmps;
    g_ctx.debug.vy_world_cmps = motion_cmd->vy_world_cmps;
    g_ctx.debug.segment_axis = geometry->segment_axis;
}

/**
 * @brief 璺緞璺熼殢涓绘洿鏂板嚱鏁般€?
 *
 * 璇ュ嚱鏁版槸璺緞璺熼殢鎺у埗閾剧殑涓诲叆鍙ｏ紝姣忎釜鎺у埗鍛ㄦ湡璋冪敤涓€娆°€?
 * 瀹冧細瀹屾垚浣嶅Э鏇存柊銆佺洰鏍囩偣鎺ㄨ繘銆佸嚑浣曞垎鏋愩€侀€熷害瑙勫垝銆佸Э鎬佽鍒掍互鍙婅溅浣撶郴杈撳嚭鍚堟垚銆?
 *
 * @param yaw_deg 褰撳墠鑸悜瑙掞紝鍗曚綅 deg銆?
 * @param out 杈撳嚭缁撴瀯浣擄紝杩斿洖褰撳墠鍛ㄦ湡杞︿綋绯婚€熷害鍛戒护涓庣姸鎬佹爣蹇椼€?
 */
void path_follow_update(float yaw_deg, path_follow_output_t *out)
{
    path_follow_geometry_t geometry = {0};
    path_follow_speed_plan_t speed_plan = {0};
    path_follow_attitude_plan_t attitude_plan = {0};
    path_follow_motion_cmd_t motion_cmd = {0};
    float yaw_error_deg = 0.0f;

    path_follow_apply_runtime_tuning();

    if (out)
    {
        out->active = 0;
        out->reached = 0;
        out->vx_cmd = 0;
        out->vy_cmd = 0;
        out->omega_cmd = 0;
        out->target_idx = g_ctx.idx;
    }

    if ((!g_ctx.active || NULL == g_ctx.path || 0 == g_ctx.steps) &&
        !g_ctx.rotate_only_active)
    {
        path_follow_clear_debug_state();
        car_direction = 0U;
        return;
    }

    update_odometry(yaw_deg);
    path_follow_sync_stay_pid_gains();

    if (g_ctx.rotate_only_active)
    {
        path_follow_plan_attitude(yaw_deg, &attitude_plan);
        yaw_error_deg = path_follow_yaw_error_deg(g_ctx.pose.yaw_deg,
                                                  attitude_plan.target_yaw_deg);

        path_follow_clear_debug_state();
        g_ctx.debug.target_yaw_deg = attitude_plan.target_yaw_deg;
        car_direction = 0U;

        if (fabsf(yaw_error_deg) <= g_ctx.yaw_tol_deg)
        {
            g_ctx.rotate_only_active = 0U;
            PID_Clear(&pid_yaw);
            path_follow_reset_control_state();
            if (out)
            {
                out->reached = 1U;
                out->active = 0U;
            }
            return;
        }

        if (out)
        {
            out->vx_cmd = 0.0f;
            out->vy_cmd = 0.0f;
            out->omega_cmd = attitude_plan.omega_cmd_radps;
            out->active = 1U;
        }
        return;
    }

    if (path_follow_handle_pause(out))
    {
        return;
    }

    if (!path_follow_prepare_geometry(&geometry, out))
    {
        if (path_follow_handle_pause(out))
        {
            return;
        }
        return;
    }

    path_follow_plan_speed(&geometry, &speed_plan);
    path_follow_build_motion_command(&geometry, &speed_plan, yaw_deg, &motion_cmd);
    path_follow_plan_attitude(yaw_deg, &attitude_plan);
    path_follow_store_debug_state(&geometry, &speed_plan, &attitude_plan, &motion_cmd);

    if (out)
    {
        out->vx_cmd = motion_cmd.vx_body_cmps;
        out->vy_cmd = motion_cmd.vy_body_cmps;
        out->omega_cmd = attitude_plan.omega_cmd_radps;
        out->active = 1U;
        out->target_idx = g_ctx.idx;
    }
}

/**
 * @brief 璺緞璺熼殢娴嬭瘯鍏ュ彛銆?
 *
 * @param yaw_deg 褰撳墠鑸悜瑙掞紝鍗曚綅 deg銆?
 * @param out 杈撳嚭缁撴瀯浣撱€?
 *
 * @note 褰撳墠瀹炵幇鐩存帴澶嶇敤姝ｅ紡鏇存柊鍑芥暟銆?
 */
void path_follow_update_test(float yaw_deg, path_follow_output_t *out)
{
    path_follow_update(yaw_deg, out);
}

/**
 * @brief 灏嗚矾寰勮窡闅忚緭鍑烘帴鍏ュ埌搴曠洏杩愬姩瀛﹂€嗚В銆?
 *
 * 璇ュ嚱鏁拌礋璐ｆ妸 `path_follow_update()` 杈撳嚭鐨勪笁杞撮€熷害鍛戒护
 * 鍐欏叆鍏ㄥ眬閫熷害缂撳瓨锛屽苟杩涗竴姝ョ敓鎴愬洓杞洰鏍囩紪鐮佸櫒閫熷害銆?
 */
void distance_speed_strategy(void)
{
    path_follow_output_t pf = {0};

    path_follow_update(eulerAngle.yaw, &pf);

    if (pf.active)
    {
        speed_three_array[0] = pf.vx_cmd;
        speed_three_array[1] = pf.vy_cmd;
        speed_three_array[2] = pf.omega_cmd;
    }
    else
    {
        speed_three_array[0] = 0.0f;
        speed_three_array[1] = 0.0f;
        speed_three_array[2] = 0.0f;
    }

    Kinematics_Inverse(speed_three_array, speed_encoder);
}

//void path_follow_request_bluetooth_report(void)
//{
//    g_path_follow_bt_report_pending = 1U;
//}

//void path_follow_service_bluetooth_report(void)
//{
//    path_follow_status_t st = {0};

//    if (!g_path_follow_bt_report_pending)
//    {
//        return;
//    }

//    g_path_follow_bt_report_pending = 0U;
//    path_follow_get_status(&st);
//    BlueSerial_Printf("POS x=%.3f y=%.3f yaw=%.1f\r\n",
//                      st.x_m,
//                      st.y_m,
//                      st.yaw_deg);
//}

/**
 * @brief 鑾峰彇璺緞璺熼殢妯″潡褰撳墠鐘舵€併€?
 *
 * @param status 鐘舵€佽緭鍑虹粨鏋勪綋銆?
 */
void path_follow_get_status(path_follow_status_t *status)
{
    if (NULL == status)
    {
        return;
    }

    status->x_m = g_ctx.pose.x_m;
    status->y_m = g_ctx.pose.y_m;
    status->yaw_deg = g_ctx.pose.yaw_deg;
    status->active = (g_ctx.active || g_ctx.rotate_only_active) ? 1U : 0U;
    status->reached = (status->active == 0U) ? 1U : 0U;
    status->paused = g_ctx.paused;
    status->yaw_only_active = g_ctx.rotate_only_active;
    status->target_idx = g_ctx.idx;
    status->distance_m = g_ctx.debug.distance_m;
    status->dir_x = g_ctx.debug.dir_x;
    status->dir_y = g_ctx.debug.dir_y;
    status->speed_ref_cmps = g_ctx.debug.speed_ref_cmps;
    status->target_yaw_deg = g_ctx.target_yaw_deg;
    status->segment_axis = g_ctx.debug.segment_axis;
    status->yaw_error_deg = path_follow_yaw_error_deg(g_ctx.pose.yaw_deg,
                                                      g_ctx.target_yaw_deg);

    if (g_ctx.path && g_ctx.idx < g_ctx.steps)
    {
        path_follow_get_compensated_target_position(g_ctx.idx,
                                                    g_ctx.path[g_ctx.idx],
                                                    &status->target_x_m,
                                                    &status->target_y_m);
    }
    else
    {
        status->target_x_m = 0.0f;
        status->target_y_m = 0.0f;
    }
}

/**
 * @brief 鍦?IPS200 灞忓箷涓婃樉绀哄綋鍓嶈矾寰勮窡闅忕姸鎬併€?
 */
void path_follow_draw_status(void)
{
    path_follow_status_t st = {0};
    path_follow_get_status(&st);

    // ips200_show_string(x, y, "Pose x y yaw:");
    ips200_show_string(0,112,"st_x_m");
    ips200_show_float(70, 112, st.x_m, 2, 4);
    ips200_show_string(0,128,"st_y_m");
    ips200_show_float(70, 128, st.y_m, 2, 4);
    ips200_show_string(0,144,"st_yaw");
    ips200_show_float(70, 144, st.yaw_deg, 3, 2);

    // ips200_show_string(x, y + 16, "Target idx/x/y:");
    ips200_show_string(0,160,"target_idx");
    ips200_show_uint(90, 160, st.target_idx, 3);
    ips200_show_string(0,176,"target_x_m");
    ips200_show_float(90, 176, st.target_x_m, 2, 3);
    ips200_show_string(0,192,"target_y_m");
    ips200_show_float(90, 192, st.target_y_m, 2, 3);
    ips200_show_string(0,208,"speed_ref");
    ips200_show_float(90, 208, st.speed_ref_cmps, 3, 1);
    ips200_show_string(0,224,"seg_axis");
    ips200_show_uint(90, 224, st.segment_axis, 1);

}

/**
 * @brief 璁＄畻涓や釜绂绘暎鐐逛箣闂寸殑鏈濆悜瑙掋€?
 *
 * @param from 璧风偣銆?
 * @param to 缁堢偣銆?
 * @return 浠庤捣鐐规寚鍚戠粓鐐圭殑瑙掑害锛屽崟浣?deg銆?
 */
float path_follow_heading_deg(Position from, Position to)
{
    float dx = (float)(to.row - from.row);
    float dy = (float)(to.col - from.col);
    if (dx == 0.0f && dy == 0.0f)
    {
        return 0.0f;
    }
    float angle_rad = atan2f(dy, dx);
    return angle_rad * (180.0f / (float)M_PI);
}

/**
 * @brief 浠庡畬鏁寸鏁ｈ矾寰勪腑鎻愬彇鎷愮偣搴忓垪銆?
 *
 * @param path 鍘熷绂绘暎璺緞銆?
 * @param path_steps 鍘熷璺緞鐐规暟閲忋€?
 * @param corner_buffer 鎷愮偣杈撳嚭缂撳瓨銆?
 * @param corner_capacity 鎷愮偣缂撳瓨瀹归噺銆?
 * @return 鎴愬姛鎻愬彇鍒扮殑鎷愮偣鏁伴噺銆?
 */
size_t path_follow_extract_corners(const Position *path, size_t path_steps,
                                   Position *corner_buffer, size_t corner_capacity)
{
    if (NULL == path || 0 == path_steps || NULL == corner_buffer || 0 == corner_capacity)
    {
        return 0;
    }

    // 浠呬竴涓偣鏃剁洿鎺ヨ繑鍥?
    if (path_steps == 1)
    {
        if (corner_capacity >= 1)
        {
            corner_buffer[0] = path[0];
            return 1;
        }
        return 0;
    }

    size_t corner_count = 0;

    // 璧风偣涓€瀹氭槸鎷愮偣
    if (corner_count >= corner_capacity)
    {
        return 0;  // 缂撳啿鍖轰笉瓒?
    }
    corner_buffer[corner_count++] = path[0];

    // 妫€鏌ヤ腑闂寸偣鏄惁鎷愬集
    for (size_t i = 1; i < path_steps - 1; i++)
    {
        // 涓婁竴娈垫柟鍚戝悜閲?
        int dx1 = path[i].col - path[i - 1].col;
        int dy1 = path[i].row - path[i - 1].row;

        // 涓嬩竴娈垫柟鍚戝悜閲?
        int dx2 = path[i + 1].col - path[i].col;
        int dy2 = path[i + 1].row - path[i].row;

        // 鏂瑰悜鍙樺寲鍒欒涓烘嫄鐐?
        if (dx1 != dx2 || dy1 != dy2)
        {
            if (corner_count >= corner_capacity)
            {
                return 0;  // 缂撳啿鍖轰笉瓒?
            }
            corner_buffer[corner_count++] = path[i];
        }
    }

    // 缁堢偣涓€瀹氭槸鎷愮偣
    if (corner_count >= corner_capacity)
    {
        return 0;  // 缂撳啿鍖轰笉瓒?
    }
    corner_buffer[corner_count++] = path[path_steps - 1];

    return corner_count;
}
